<a href="https://colab.research.google.com/github/filiprulisek/PythonDataIES/blob/master/project_hadzic_rulisek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project - Bundesliga Table

---

## Importing necessary libraries

In [3]:
import pandas as pd
import json
from IPython.display import HTML, display
import os
import requests
!pip install cloudscraper
import cloudscraper
from bs4 import BeautifulSoup

Requirement already satisfied: cloudscraper in /usr/local/lib/python3.10/dist-packages (1.2.71)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.10/dist-packages (from cloudscraper) (3.1.2)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python3.10/dist-packages (from cloudscraper) (2.32.3)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from cloudscraper) (1.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.9.2->cloudscraper) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.9.2->cloudscraper) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.9.2->cloudscraper) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.9.2->cloudscraper) (2024.7.4)

## Downloading raw data for individual rounds from sofascore.com

In [4]:
import requests

# Define a list to store all matches
all_matches = []

# Loop through rounds 1 to 34
for round_number in range(1, 35):
    url = f"https://www.sofascore.com/api/v1/unique-tournament/35/season/52608/events/round/{round_number}"
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        matches = response.json()["events"]
        all_matches.append(matches)
    else:
        print(f"Failed to retrieve matches for round {round_number}")

# Print all matches
for idx, matches in enumerate(all_matches, start=1):
    print(f"Matches for round {idx}:")
    for match in matches:
        print(match)
    print("\n")

Matches for round 1:
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'Jabsxdb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 2, 'homeTeam': {'name': 'SV Werder Bremen', 'slug': 'sv-werder-bremen', 'shortName': 'Bremen', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 95412, 'nameCode': 'SVW', 'disabled': False, 'national': False, 'type': 0, 'id': 2534, 'subTeams': [], 'teamColors': {'primary': '#009966', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'فيردر بريمن', 'ru': 'Вердер Бремен'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'FC Bayern München', 'slug': 'fc-bayern-munchen', 'shortName': 'Bayern', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 1797611, 'nameCode': 'BAY', 'disabled': False, 'national': False, 'type': 0, 'id': 2672, 'subTeams': [], 'teamColors': {'primary': '#cf142f', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نادي بايرن ميونيخ', 'ru': 'Бавария Мюнхен'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 0, 'display': 0, 'period1': 0, 'period2': 0, 'normaltime': 0}, 'awayScore': {'current': 4, 'display': 4, 'period1': 1, 'period2': 3, 'normaltime': 4}, 'time': {'injuryTime1': 3, 'injuryTime2': 6, 'currentPeriodStartTimestamp': 1692390482}, 'changes': {'changes': ['homeScore.period2', 'homeScore.normaltime', 'awayScore.period2', 'awayScore.normaltime'], 'changeTimestamp': 1692390630}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396480, 'crowdsourcingEnabled': False, 'startTimestamp': 1692383400, 'slug': 'fc-bayern-munchen-sv-werder-bremen', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'GdbskCo', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'Bayer 04 Leverkusen', 'slug': 'bayer-04-leverkusen', 'shortName': 'Leverkusen', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 964459, 'nameCode': 'B04', 'disabled': False, 'national': False, 'type': 0, 'id': 2681, 'subTeams': [], 'teamColors': {'primary': '#000000', 'secondary': '#ff2222', 'text': '#ff2222'}, 'fieldTranslations': {'nameTranslation': {'ar': 'باير ليفركوزن', 'ru': 'Байер Леверкузен'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'RB Leipzig', 'slug': 'rb-leipzig', 'shortName': 'Leipzig', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 607052, 'nameCode': 'RBL', 'disabled': False, 'national': False, 'type': 0, 'id': 36360, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#dd0000', 'text': '#dd0000'}, 'fieldTranslations': {'nameTranslation': {'ar': 'آر بي لايبزيغ', 'ru': 'РБ Лейпциг'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 3, 'display': 3, 'period1': 2, 'period2': 1, 'normaltime': 3}, 'awayScore': {'current': 2, 'display': 2, 'period1': 1, 'period2': 1, 'normaltime': 2}, 'time': {'injuryTime1': 3, 'injuryTime2': 5, 'currentPeriodStartTimestamp': 1692455626}, 'changes': {'changes': ['status.code', 'status.description', 'status.type'], 'changeTimestamp': 1692458691}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396478, 'crowdsourcingEnabled': False, 'startTimestamp': 1692451800, 'slug': 'rb-leipzig-bayer-04-leverkusen', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'Cabsacb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 3, 'homeTeam': {'name': 'FC Augsburg', 'slug': 'fc-augsburg', 'shortName': 'Augsburg', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 77740, 'nameCode': 'FCA', 'disabled': False, 'national': False, 'type': 0, 'id': 2600, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#cd1719', 'text': '#cd1719'}, 'fieldTranslations': {'nameTranslation': {'ar': 'إف سي أوجسبورغ', 'ru': 'Аугсбург'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': "Borussia M'gladbach", 'slug': 'borussia-mgladbach', 'shortName': "M'gladbach", 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 145123, 'nameCode': 'BMG', 'disabled': False, 'national': False, 'type': 0, 'id': 2527, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#000000', 'text': '#000000'}, 'fieldTranslations': {'nameTranslation': {'ar': 'بوروسيا مونشنغلادباخ', 'ru': 'Боруссия Мёнхенгладбах'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 4, 'display': 4, 'period1': 3, 'period2': 1, 'normaltime': 4}, 'awayScore': {'current': 4, 'display': 4, 'period1': 3, 'period2': 1, 'normaltime': 4}, 'time': {'injuryTime1': 5, 'injuryTime2': 6, 'currentPeriodStartTimestamp': 1692455870}, 'changes': {'changes': ['status.code', 'status.description', 'status.type', 'awayScore.period2', 'awayScore.normaltime'], 'changeTimestamp': 1692459067}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396473, 'crowdsourcingEnabled': False, 'startTimestamp': 1692451800, 'slug': 'fc-augsburg-borussia-mgladbach', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'Nabsubb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 2, 'homeTeam': {'name': 'TSG Hoffenheim', 'slug': 'tsg-hoffenheim', 'shortName': 'Hoffenheim', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 107273, 'nameCode': 'TSG', 'disabled': False, 'national': False, 'type': 0, 'id': 2569, 'subTeams': [], 'teamColors': {'primary': '#1f5da6', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نادي هوفنهايم', 'ru': 'Хоффенхайм'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'SC Freiburg', 'slug': 'sc-freiburg', 'shortName': 'Freiburg', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 150267, 'nameCode': 'SCF', 'disabled': False, 'national': False, 'type': 0, 'id': 2538, 'subTeams': [], 'teamColors': {'primary': '#cc3333', 'secondary': '#000000', 'text': '#000000'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نادي فرايبورغ', 'ru': 'Фрайбург'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 1, 'display': 1, 'period1': 0, 'period2': 1, 'normaltime': 1}, 'awayScore': {'current': 2, 'display': 2, 'period1': 2, 'period2': 0, 'normaltime': 2}, 'time': {'injuryTime1': 3, 'injuryTime2': 5, 'currentPeriodStartTimestamp': 1692455875}, 'changes': {'changes': ['status.code', 'status.description', 'status.type'], 'changeTimestamp': 1692458889}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396475, 'crowdsourcingEnabled': False, 'startTimestamp': 1692451800, 'slug': 'tsg-hoffenheim-sc-freiburg', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'RabsCdb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'VfB Stuttgart', 'slug': 'vfb-stuttgart', 'shortName': 'Stuttgart', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 205632, 'nameCode': 'VFB', 'disabled': False, 'national': False, 'type': 0, 'id': 2677, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#ff0000', 'text': '#ff0000'}, 'fieldTranslations': {'nameTranslation': {'ar': 'شتوتجارت', 'ru': 'Штутгарт'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': 'VfL Bochum 1848', 'slug': 'vfl-bochum-1848', 'shortName': 'Bochum', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 79906, 'nameCode': 'BOC', 'disabled': False, 'national': False, 'type': 0, 'id': 2542, 'subTeams': [], 'teamColors': {'primary': '#6666ff', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'بوخوم', 'ru': 'Бохум'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 5, 'display': 5, 'period1': 2, 'period2': 3, 'normaltime': 5}, 'awayScore': {'current': 0, 'display': 0, 'period1': 0, 'period2': 0, 'normaltime': 0}, 'time': {'injuryTime1': 5, 'injuryTime2': 0, 'currentPeriodStartTimestamp': 1692456135}, 'changes': {'changes': ['time.injuryTime2', 'status.code', 'status.description', 'status.type'], 'changeTimestamp': 1692458870}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396472, 'crowdsourcingEnabled': False, 'startTimestamp': 1692451800, 'slug': 'vfb-stuttgart-vfl-bochum-1848', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'zabsKrc', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'VfL Wolfsburg', 'slug': 'vfl-wolfsburg', 'shortName': 'Wolfsburg', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 119071, 'nameCode': 'WOB', 'disabled': False, 'national': False, 'type': 0, 'id': 2524, 'subTeams': [], 'teamColors': {'primary': '#64b42d', 'secondary': '#ffffff', 'text': '#ffffff'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نادي فولفسبورغ', 'ru': 'Вольфсбург'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': '1. FC Heidenheim', 'slug': '1-fc-heidenheim', 'shortName': 'Heidenheim', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 60077, 'nameCode': 'FCH', 'disabled': False, 'national': False, 'type': 0, 'id': 5885, 'subTeams': [], 'teamColors': {'primary': '#243475', 'secondary': '#400040', 'text': '#400040'}, 'fieldTranslations': {'nameTranslation': {'ar': '1. نادي هايدنهايم', 'ru': '1. ФК Хайденхайм'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 2, 'display': 2, 'period1': 2, 'period2': 0, 'normaltime': 2}, 'awayScore': {'current': 0, 'display': 0, 'period1': 0, 'period2': 0, 'normaltime': 0}, 'time': {'injuryTime1': 6, 'injuryTime2': 5, 'currentPeriodStartTimestamp': 1692455868}, 'changes': {'changes': ['status.code', 'status.description', 'status.type'], 'changeTimestamp': 1692458888}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396474, 'crowdsourcingEnabled': False, 'startTimestamp': 1692451800, 'slug': '1-fc-heidenheim-vfl-wolfsburg', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}
{'tournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'uniqueTournament': {'name': 'Bundesliga', 'slug': 'bundesliga', 'primaryColorHex': '#e2080e', 'secondaryColorHex': '#8e0902', 'category': {'name': 'Germany', 'slug': 'germany', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'id': 30, 'flag': 'germany', 'alpha2': 'DE'}, 'userCount': 844252, 'crowdsourcingEnabled': False, 'hasPerformanceGraphFeature': True, 'id': 35, 'hasEventPlayerStatistics': True, 'displayInverseHomeAwayTeams': False}, 'priority': 605, 'isGroup': False, 'isLive': False, 'id': 42}, 'season': {'name': 'Bundesliga 23/24', 'year': '23/24', 'editor': False, 'id': 52608}, 'roundInfo': {'round': 1}, 'customId': 'wdbsydb', 'status': {'code': 100, 'description': 'Ended', 'type': 'finished'}, 'winnerCode': 1, 'homeTeam': {'name': 'Borussia Dortmund', 'slug': 'borussia-dortmund', 'shortName': 'Dortmund', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 1275006, 'nameCode': 'BVB', 'disabled': False, 'national': False, 'type': 0, 'id': 2673, 'subTeams': [], 'teamColors': {'primary': '#ffe600', 'secondary': '#000000', 'text': '#000000'}, 'fieldTranslations': {'nameTranslation': {'ar': 'بوروسيا دورتموند', 'ru': 'Боруссия Дортмунд'}, 'shortNameTranslation': {}}}, 'awayTeam': {'name': '1. FC Köln', 'slug': '1-fc-koln', 'shortName': 'Köln', 'gender': 'M', 'sport': {'name': 'Football', 'slug': 'football', 'id': 1}, 'userCount': 99690, 'nameCode': 'KOE', 'disabled': False, 'national': False, 'type': 0, 'id': 2671, 'subTeams': [], 'teamColors': {'primary': '#ffffff', 'secondary': '#e30613', 'text': '#e30613'}, 'fieldTranslations': {'nameTranslation': {'ar': 'نادي كولن', 'ru': 'Кёльн'}, 'shortNameTranslation': {}}}, 'homeScore': {'current': 1, 'display': 1, 'period1': 0, 'period2': 1, 'normaltime': 1}, 'awayScore': {'current': 0, 'display': 0, 'period1': 0, 'period2': 0, 'normaltime': 0}, 'time': {'injuryTime1': 2, 'injuryTime2': 6, 'currentPeriodStartTimestamp': 1692466476}, 'changes': {'changes': ['status.code', 'status.description', 'status.type'], 'changeTimestamp': 1692469583}, 'hasGlobalHighlights': False, 'hasXg': True, 'hasEventPlayerStatistics': True, 'hasEventPlayerHeatMap': True, 'detailId': 1, 'crowdsourcingDataDisplayEnabled': False, 'id': 11396479, 'crowdsourcingEnabled': False, 'startTimestamp': 1692462600, 'slug': 'borussia-dortmund-1-fc-koln', 'finalResultOnly': False, 'feedLocked': True, 'isEditor': False}

In [9]:
import requests

# Define a list to store all matches
all_matches = []

# Loop through rounds 1 to 34
for round_number in range(1, 35):
    url = f"https://www.sofascore.com/api/v1/unique-tournament/35/season/52608/events/round/{round_number}"
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        matches = response.json()["events"]
        all_matches.append(matches)
    else:
        print(f"Failed to retrieve matches for round {round_number}")


df_matches=pd.DataFrame(all_matches)

df_matches_ids = []
for i in range(34):
  for j in range(9):
   df_matches_ids.append(df_matches[j][i]["id"])


for game in df_matches["id"]:
  round_games.append(game)

    headersi = {
        "authority": "api.sofascore.com",
        "accept": "*/*",
        "accept-language": "cs-CZ,cs;q=0.9",
        "cache-control": "max-age=0",
        "if-none-match": 'W/\^"4a86ffe035^\^"^',
        "priority": "u=1, i",
        "referer": "https://www.sofascore.com/borussia-dortmund-tsg-hoffenheim/ubbsydb",
        "sec-ch-ua": '^\^"Not/A)Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"126^\^", ^\^"Google Chrome^\^";v=^\^"126^\^"^',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '^\^"Windows^\^"^',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "x-requested-with": "b75996"
    }


filenames = []
all_incidents=[]
for game in df_matches_ids:

        response = requests.get(f"https://www.sofascore.com/api/v1/event/{game}/incidents", headers=headersi)
        filename = f"incidents_{game}"
        globals()[f"incidents_{game}"] = response.json()
        incidents = response.json()  # Store incidents directly instead of using globals()
        all_incidents.append(incidents)
        filenames.append(filename)

globals()[f"round{number}"] = filenames

IndentationError: unexpected indent (<ipython-input-9-261d8fb735a0>, line 30)

In [10]:
import requests
import pandas as pd

# Define a list to store all matches
all_matches = []

# Loop through rounds 1 to 34
for round_number in range(1, 35):
    url = f"https://www.sofascore.com/api/v1/unique-tournament/35/season/52608/events/round/{round_number}"
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        matches = response.json().get("events", [])
        all_matches.extend(matches)  # Use extend to flatten the list of matches
    else:
        print(f"Failed to retrieve matches for round {round_number}")

# Convert list of matches into a DataFrame
df_matches = pd.DataFrame(all_matches)

# Extract match IDs
df_matches_ids = df_matches["id"].tolist()

# Define headers for incidents API requests
headers = {
    "authority": "api.sofascore.com",
    "accept": "*/*",
    "accept-language": "cs-CZ,cs;q=0.9",
    "cache-control": "max-age=0",
    "if-none-match": 'W/"4a86ffe035"',
    "priority": "u=1, i",
    "referer": "https://www.sofascore.com/borussia-dortmund-tsg-hoffenheim/ubbsydb",
    "sec-ch-ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "x-requested-with": "b75996"
}

# Define lists to store filenames and incidents
filenames = []
all_incidents = []

# Fetch incidents for each game
for game_id in df_matches_ids:
    response = requests.get(f"https://www.sofascore.com/api/v1/event/{game_id}/incidents", headers=headers)

    if response.status_code == 200:
        incidents = response.json()
        all_incidents.append(incidents)
        filenames.append(f"incidents_{game_id}")
    else:
        print(f"Failed to retrieve incidents for game ID {game_id}")

# Optionally store incidents in a dictionary or another structure
# incidents_data = {f"incidents_{game_id}": incidents for game_id, incidents in zip(df_matches_ids, all_incidents)}

## Getting match IDs for each match UNNECESSARY

In [5]:
df_matches=pd.DataFrame(all_matches)

df_matches_ids = []
for i in range(34):
  for j in range(9):
   df_matches_ids.append(df_matches[j][i]["id"])

print(df_matches_ids)

[11396480, 11396478, 11396473, 11396475, 11396472, 11396474, 11396479, 11396477, 11396476, 11396468, 11396464, 11396467, 11396462, 11396471, 11396465, 11396466, 11396469, 11396470, 11396461, 11396459, 11396454, 11396455, 11396457, 11396453, 11396456, 11396458, 11396460, 11396452, 11396447, 11396449, 11396451, 11396450, 11396448, 11396446, 11396445, 11396444, 11396436, 11396441, 11396442, 11396440, 11396435, 11396443, 11396437, 11396439, 11396438, 11396430, 11396426, 11396429, 11396431, 11396427, 11396432, 11396434, 11396428, 11396433, 11396420, 11396424, 11396418, 11396422, 11396417, 11396419, 11396423, 11396425, 11396421, 11396416, 11396415, 11396408, 11396413, 11396410, 11396414, 11396411, 11396412, 11396409, 11396401, 11396403, 11396400, 11396407, 11396402, 11396398, 11396406, 11396405, 11396404, 11396390, 11396393, 11396397, 11396394, 11396396, 11396392, 11396399, 11396395, 11396391, 11396381, 11396385, 11396388, 11396386, 11396387, 11396389, 11396383, 11396382, 11396384, 11396376, 11396378, 11396380, 11396377, 11396373, 11396375, 11396379, 11396372, 11396374, 11396363, 11396367, 11396370, 11396366, 11396364, 11396368, 11396369, 11396365, 11880344, 11396357, 11396354, 11396361, 11396360, 11396356, 11396358, 11396362, 11396355, 11396359, 11396347, 11396348, 11396345, 11396344, 11396349, 11396352, 11396351, 11396350, 11396353, 11396338, 11396346, 11396339, 11396343, 11396336, 11396342, 11396341, 11396337, 11396340, 11396335, 11396330, 11396332, 11396329, 11396334, 11396333, 11396327, 11396328, 11396331, 11396319, 11396321, 11396318, 11396324, 11396320, 11396325, 11396326, 11396322, 11996503, 11396314, 11396310, 11396311, 11396312, 11396309, 11396313, 11396315, 11396317, 11396316, 11396301, 11396304, 11396299, 11396308, 11396306, 11396302, 11396303, 11396305, 11396307, 11396300, 11396297, 11396295, 11396296, 11396292, 11396293, 11396298, 11396291, 11396294, 11396286, 11396281, 11396287, 11396283, 11396285, 11396288, 11396289, 11396290, 11396284, 11396278, 11396279, 11396276, 11396275, 11396273, 11396282, 11396277, 11396280, 11396274, 11396271, 11396263, 11396272, 11396269, 11396265, 11396266, 11396270, 11396268, 11396267, 11396261, 11396258, 11396264, 11396262, 11396260, 11396254, 11396255, 11396257, 11396259, 11396248, 11396247, 11396253, 11396250, 11396246, 11396251, 11396249, 11396252, 11396256, 11396243, 11396241, 11396242, 11396244, 11396240, 11396245, 11396238, 11396237, 11396239, 11396234, 11396226, 11396230, 11396235, 11396232, 11396233, 11396236, 11396229, 11396231, 11396221, 11396224, 11396223, 11396227, 11396225, 11396222, 11396220, 11396219, 11396228, 11396215, 11396210, 11396214, 11396211, 11396213, 11396217, 11396212, 11396218, 11396216, 11396203, 11396202, 11396209, 11396208, 11396207, 11396206, 11396204, 11396205, 11396201, 11396195, 11396200, 11396194, 11396193, 11396196, 11396197, 11396199, 11396198, 11396191, 11396182, 11396185, 11396186, 11396189, 11396188, 11396192, 11396183, 11396190, 11396184, 11396173, 11396180, 11396179, 11396181, 11396177, 11396175, 11396176, 11396174, 11396178]

## Downloading individual matches from sofascore.com (this takes around 10 to 12 minutes)

In [6]:
#All match info for all rounds and all games
numbers = list(range(1, 35))
for number in numbers:
    url = f"https://www.sofascore.com/api/v1/unique-tournament/35/season/52608/events/round/{number}"
    payload = {}
   # headers = {
        "authority": "api.sofascore.com",
        "accept": "*/*",
        "accept-language": "cs-CZ,cs;q=0.9",
        "cache-control": "max-age=0",
        "cookie": "_gcl_au=1.1.560678774.1718992025; _ga=GA1.1.1160595185.1718992026; FCCDCF=^%^5Bnull^%^2Cnull^%^2Cnull^%^2C^%^5B^%^22CQAj5kAQAj5kAEsACBCSA6EoAP_gAEPgAA6II3gB5C5ETSFBYH51KIsEYAEHwAAAIsAgAAYBAQABQBKQAIQCAGAAEAhAhCACgAAAIEYBIAEACAAQAAAAAAAAIAAEIAAQAAAIICAAAAAAAABIAAAIAAAAEAAAwCAABAAA0AgEAJIISMgAAAAAAAAAAgAAAAAAAgAAAEhAAAEIAAAAACgAEABAEAAAAAEIABBII3gB5C5ETSFBYHhVIIMEIAERQAAAIsAgAAQBAQAAQBKQAIQCEGAAAAgAACAAAAAAIEQBIAEAAAgAAAAAAAAAIAAEAAAAAAAIICAAAAAAAABAAAAIAAAAAAAAwCAABAAAwQhEAJIASEgAAAAgAAAAAoAAAAAAAgAAAEhAAAEAAAAAAAAAEAAAEAAAAAAAABBIAAA.dnAACAgAAAA^%^22^%^2C^%^222~70.89.108.149.211.313.358.415.486.540.621.981.1029.1046.1092.1097.1126.1205.1301.1516.1558.1584.1598.1651.1697.1716.1753.1810.1832.1985.2328.2373.2440.2571.2572.2575.2577.2628.2642.2677.2767.2860.2878.2887.2922.3182.3190.3234.3290.3292.3331.10631~dv.^%^22^%^2C^%^22883EFD97-E535-4765-863B-18B3B05EEBFD^%^22^%^5D^%^5D; __qca=P0-1975105721-1719681623522; _lr_env_src_ats=false; __gads=ID=1ec4056dd7111528:T=1718992030:RT=1720002378:S=ALNI_MZYumIML9JUuggc9N2NSdnxjdRkOA; __gpi=UID=00000e5f826baab6:T=1718992030:RT=1720002378:S=ALNI_MYK3lu4itGKDoE8Zb2XyLYO6nacAw; __eoi=ID=367149c515d8c92b:T=1718992030:RT=1720002378:S=AA-AfjYNKzhH8m4u6j7Sh6KQJnHc; FCNEC=^%^5B^%^5B^%^22AKsRol_IFwCPamLzKIa_CgyE6DjbMXunCOrzjEctoMbOZZXtwSOlnOmsbkfRajj0jv2rN9bTuaeNq5kNJQuXM9etT-zc0STmeB8BHIMZffLjKrvke_iZX7V8wjkIjdZ3ZBkXWNcl47D6bwxmQUDI1bMN0WTwbo1xhg^%^3D^%^3D^%^22^%^5D^%^5D; _ga_QH2YGS7BB4=GS1.1.1720002376.22.1.1720002577.0.0.0; _ga_3KF4XTPHC4=GS1.1.1720002376.22.1.1720002577.22.0.0; _ga_HNQ9P9MGZR=GS1.1.1720002378.21.1.1720002577.25.0.0^",
        "priority": "u=1, i",
        "referer": "https://www.sofascore.com/tournament/football/germany/bundesliga/35",
        "sec-ch-ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '"Windows"',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "x-requested-with": "b75996"
    }

    response = requests.get(url, headers=headers, data=payload)

    matches = response.json()["events"]
    df_matches = pd.DataFrame(matches)
    round_games = []
    for game in df_matches["id"]:
        round_games.append(game)

    headersi = {
        "authority": "api.sofascore.com",
        "accept": "*/*",
        "accept-language": "cs-CZ,cs;q=0.9",
        "cache-control": "max-age=0",
        "if-none-match": 'W/\^"4a86ffe035^\^"^',
        "priority": "u=1, i",
        "referer": "https://www.sofascore.com/borussia-dortmund-tsg-hoffenheim/ubbsydb",
        "sec-ch-ua": '^\^"Not/A)Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"126^\^", ^\^"Google Chrome^\^";v=^\^"126^\^"^',
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": '^\^"Windows^\^"^',
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "x-requested-with": "b75996"
    }

    filenames = []

 #   for game in df_matches_ids:
 #       response = requests.get(f"https://www.sofascore.com/api/v1/event/{game}/incidents", headers=headersi)
#      filename = f"incidents_{game}"
#       globals()[f"incidents_{game}"] = response.json()
#      filenames.append(filename)

#    globals()[f"round{number}"] = filenames

all_incidents=[]
for game in df_matches_ids:

        response = requests.get(f"https://www.sofascore.com/api/v1/event/{game}/incidents", headers=headersi)
        filename = f"incidents_{game}"
        globals()[f"incidents_{game}"] = response.json()
        incidents = response.json()  # Store incidents directly instead of using globals()
        all_incidents.append(incidents)
        filenames.append(filename)

globals()[f"round{number}"] = filenames

## Creating two functions, one that extracts important match events from raw data (downloaded above), second that creates readable data frame

In [11]:
import pandas as pd

def extract_events(game_data):
    events = []

    for incident in game_data['incidents']:
        if incident['incidentType'] == 'goal':
            goal_event = {
                'Event': 'Goal',
                'Minute': incident['time'],
                'Scorer': incident.get('player', {}).get('shortName', '-'),
                'Assist': incident.get('assist1', {}).get('shortName', '-'),
                'Team': 'Home' if incident.get('isHome', False) else 'Away'
            }
            events.append(goal_event)

        elif incident['incidentType'] == 'substitution':
            sub_event = {
                'Event': 'Substitution',
                'Minute': incident['time'],
                'Player In': incident.get('playerIn', {}).get('shortName', '-'),
                'Player Out': incident.get('playerOut', {}).get('shortName', '-'),
                'Team': 'Home' if incident.get('isHome', False) else 'Away'
            }
            events.append(sub_event)

        elif incident['incidentType'] == 'card':
            card_event = {
                'Event': 'Card',
                'Minute': incident['time'],
                'Player': incident.get('player', {}).get('shortName', '-'),
                'Reason': incident.get('reason', '-'),
                'Card Type': incident.get('incidentClass', '-'),  # 'yellow', 'red', etc.
                'Team': 'Home' if incident.get('isHome', False) else 'Away'
            }
            events.append(card_event)

        elif incident['incidentType'] == 'missed_penalty':
            missed_penalty_event = {
                'Event': 'Missed Penalty',
                'Minute': incident['time'],
                'Player': incident.get('player', {}).get('shortName', '-'),
                'Team': 'Home' if incident.get('isHome', False) else 'Away'
            }
            events.append(missed_penalty_event)

        elif incident['incidentType'] == 'var':
            var_event = {
                'Event': 'VAR',
                'Minute': incident['time'],
                'Player': incident.get('player', {}).get('shortName', '-'),
                'Reason': incident.get('reason', '-'),
                'Team': 'Home' if incident.get('isHome', False) else 'Away'
            }
            events.append(var_event)

    return events

def create_dataframe(events):
    # Create separate dataframes for home and away events
    df_home = pd.DataFrame([event for event in events if event['Team'] == 'Home'])
    df_away = pd.DataFrame([event for event in events if event['Team'] == 'Away'])

    # Rename columns to reflect home and away differentiation
    df_home.columns = [f'Home {col}' if col != 'Minute' else col for col in df_home.columns]
    df_away.columns = [f'Away {col}' if col != 'Minute' else col for col in df_away.columns]

    # Merge home and away dataframes on the Minute column
    # Concatenate the DataFrames
    df = pd.concat([df_home, df_away])

    # Sort the DataFrame by 'Minute'
    df = df.sort_values('Minute')

    # Reset the index if needed
    df = df.reset_index(drop=True)

    return df

# Example usage with the updated functions
game_data = all_incidents[22]  # Assuming all_incidents is already defined
events = extract_events(game_data)
df = create_dataframe(events)
print(df)

      Home Event  Minute Home Player In Home Player Out Home Team Home Scorer  \
0           Card      10            NaN             NaN      Home         NaN
1           Card      25            NaN             NaN      Home         NaN
2            NaN      36            NaN             NaN       NaN         NaN
3            NaN      43            NaN             NaN       NaN         NaN
4           Goal      45            NaN             NaN      Home   J. Brooks
5   Substitution      59        R. Skov       M. Bülter      Home         NaN
6           Goal      60            NaN             NaN      Home    M. Beier
7   Substitution      68     M. Berisha        M. Beier      Home         NaN
8            NaN      68            NaN             NaN       NaN         NaN
9            NaN      68            NaN             NaN       NaN         NaN
10           NaN      68            NaN             NaN       NaN         NaN
11          Goal      74            NaN             NaN      Home     R. Skov
12           NaN      75            NaN             NaN       NaN         NaN
13           NaN      78            NaN             NaN       NaN         NaN
14           NaN      83            NaN             NaN       NaN         NaN
15  Substitution      90  D. Samassékou     A. Kramarić      Home         NaN

    Home Assist  Home Player        Home Reason Home Card Type    Away Event  \
0           NaN  W. Weghorst                  -         yellow           NaN
1           NaN     I. Bebou  Off the ball foul         yellow           NaN
2           NaN          NaN                NaN            NaN          Goal
3           NaN          NaN                NaN            NaN          Card
4     M. Bülter          NaN                NaN            NaN           NaN
5           NaN          NaN                NaN            NaN           NaN
6       R. Skov          NaN                NaN            NaN           NaN
7           NaN          NaN                NaN            NaN           NaN
8           NaN          NaN                NaN            NaN  Substitution
9           NaN          NaN                NaN            NaN  Substitution
10          NaN          NaN                NaN            NaN  Substitution
11  A. Kramarić          NaN                NaN            NaN           NaN
12          NaN          NaN                NaN            NaN          Card
13          NaN          NaN                NaN            NaN  Substitution
14          NaN          NaN                NaN            NaN  Substitution
15          NaN          NaN                NaN            NaN           NaN

   Away Player In Away Player Out Away Team  Away Player Away Reason  \
0             NaN             NaN       NaN          NaN         NaN
1             NaN             NaN       NaN          NaN         NaN
2             NaN             NaN      Away          NaN         NaN
3             NaN             NaN      Away     J. Mæhle        Foul
4             NaN             NaN       NaN          NaN         NaN
5             NaN             NaN       NaN          NaN         NaN
6             NaN             NaN       NaN          NaN         NaN
7             NaN             NaN       NaN          NaN         NaN
8      K. Paredes        T. Tomás      Away          NaN         NaN
9         A. Sarr        L. Majer      Away          NaN         NaN
10        R. Baku        J. Mæhle      Away          NaN         NaN
11            NaN             NaN       NaN          NaN         NaN
12            NaN             NaN      Away  M. Svanberg    Argument
13    Y. Gerhardt     M. Svanberg      Away          NaN         NaN
14    J. Kamiński        V. Černý      Away          NaN         NaN
15            NaN             NaN       NaN          NaN         NaN

   Away Card Type Away Scorer Away Assist
0             NaN         NaN         NaN
1             NaN         NaN         NaN
2             NaN    T. Tomás     J. Wind
3          yellow         NaN         NaN
4             NaN         NaN         NaN
5             NaN         NaN         NaN
6             NaN         NaN         NaN
7             NaN         NaN         NaN
8             NaN         NaN         NaN
9             NaN         NaN         NaN
10            NaN         NaN         NaN
11            NaN         NaN         NaN
12         yellow         NaN         NaN
13            NaN         NaN         NaN
14            NaN         NaN         NaN
15            NaN         NaN         NaN

## This is how one particular data frame with important match information looks like

In [12]:
create_dataframe(extract_events(all_incidents[1]))

,Home Event,Minute,Home Player In,Home Player Out,Home Team,Home Player,Home Reason,Home Card Type,Home Scorer,Home Assist,Away Event,Away Player In,Away Player Out,Away Team,Away Player,Away Reason,Away Card Type,Away Scorer,Away Assist
0,Goal,24,NaN,NaN,Home,NaN,NaN,NaN,J. Frimpong,V. O. Boniface,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Goal,35,NaN,NaN,Home,NaN,NaN,NaN,J. Tah,J. Hofmann,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Goal,NaN,NaN,Away,NaN,NaN,NaN,D. Olmo,D. Raum
3,NaN,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Substitution,C. Lukeba,N. Seiwald,Away,NaN,NaN,NaN,NaN,NaN
4,NaN,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Card,NaN,NaN,Away,N. Seiwald,Foul,yellow,NaN,NaN
5,NaN,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Substitution,Y. Poulsen,T. Werner,Away,NaN,NaN,NaN,NaN,NaN
6,NaN,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Substitution,K. Kampl,X. Simons,Away,NaN,NaN,NaN,NaN,NaN
7,Goal,64,NaN,NaN,Home,NaN,NaN,NaN,F. Wirtz,J. Frimpong,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Card,69,NaN,NaN,Home,V. O. Boniface,Argument,yellow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Goal,NaN,NaN,Away,NaN,NaN,NaN,L. Openda,M. Simakan
10,Substitution,75,R. Andrich,F. Wirtz,Home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Substitution,E. Forsberg,L. Openda,Away,NaN,NaN,NaN,NaN,NaN
12,Substitution,78,Arthur,J. Frimpong,Home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Card,NaN,NaN,Away,C. Lukeba,Foul,yellow,NaN,NaN
14,NaN,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Substitution,F. Carvalho,X. Schlager,Away,NaN,NaN,NaN,NaN,NaN
15,Substitution,89,A. Hložek,J. Hofmann,Home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Substitution,89,N. Amiri,V. O. Boniface,Home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## All of them

In [13]:
for i in range(306):
  print(create_dataframe(extract_events(all_incidents[i])))

Výstupní stream byl oříznut na posledních 5000 řádků.
      Home Event  Minute Home Scorer Home Assist Home Team  Home Player In  \
0            NaN       2         NaN         NaN       NaN             NaN
1           Goal      10     R. Doan    L. Höler      Home             NaN
2            NaN      40         NaN         NaN       NaN             NaN
3            NaN      53         NaN         NaN       NaN             NaN
4   Substitution      62         NaN         NaN      Home     P. Lienhart
5   Substitution      62         NaN         NaN      Home      F. Muslija
6   Substitution      62         NaN         NaN      Home  M. Gregoritsch
7           Card      72         NaN         NaN      Home             NaN
8   Substitution      76         NaN         NaN      Home      M. Philipp
9   Substitution      76         NaN         NaN      Home       Y. Keitel
10           NaN      76         NaN         NaN       NaN             NaN
11          Goal      79   Y. Keitel           -      Home             NaN
12           NaN      83         NaN         NaN       NaN             NaN
13           NaN      83         NaN         NaN       NaN             NaN
14           NaN      89         NaN         NaN       NaN             NaN

   Home Player Out Home Player Home Reason Home Card Type    Away Event  \
0              NaN         NaN         NaN            NaN          Goal
1              NaN         NaN         NaN            NaN           NaN
2              NaN         NaN         NaN            NaN          Goal
3              NaN         NaN         NaN            NaN          Goal
4        M. Ginter         NaN         NaN            NaN           NaN
5         V. Grifo         NaN         NaN            NaN           NaN
6        R. Sallai         NaN         NaN            NaN           NaN
7              NaN   N. Höfler        Foul         yellow           NaN
8         L. Höler         NaN         NaN            NaN           NaN
9          M. Röhl         NaN         NaN            NaN           NaN
10             NaN         NaN         NaN            NaN  Substitution
11             NaN         NaN         NaN            NaN           NaN
12             NaN         NaN         NaN            NaN  Substitution
13             NaN         NaN         NaN            NaN  Substitution
14             NaN         NaN         NaN            NaN  Substitution

   Away Player In Away Player Out Away Team Away Scorer  Away Assist
0             NaN             NaN      Away    F. Wirtz  A. Grimaldo
1             NaN             NaN       NaN         NaN          NaN
2             NaN             NaN      Away   A. Hložek            -
3             NaN             NaN      Away   P. Schick  J. Frimpong
4             NaN             NaN       NaN         NaN          NaN
5             NaN             NaN       NaN         NaN          NaN
6             NaN             NaN       NaN         NaN          NaN
7             NaN             NaN       NaN         NaN          NaN
8             NaN             NaN       NaN         NaN          NaN
9             NaN             NaN       NaN         NaN          NaN
10        A. Adli       P. Schick      Away         NaN          NaN
11            NaN             NaN       NaN         NaN          NaN
12     R. Andrich       A. Hložek      Away         NaN          NaN
13       N. Tella     J. Frimpong      Away         NaN          NaN
14     E. Tapsoba     E. Palacios      Away         NaN          NaN
      Home Event  Minute Home Scorer Home Assist Home Team Home Player  \
0            NaN      13         NaN         NaN       NaN         NaN
1           Goal      33  K. Adeyemi    D. Malen      Home         NaN
2   Substitution      65         NaN         NaN      Home         NaN
3   Substitution      65         NaN         NaN      Home         NaN
4            NaN      67         NaN         NaN       NaN         NaN
5   Substitution      74         NaN         NaN      Home         NaN
6            NaN      74         NaN         NaN       NaN         NaN
7            NaN      74         NaN         NaN       NaN         NaN
8            NaN      80         NaN         NaN       NaN         NaN
9           Goal      81  M. Hummels   J. Brandt      Home         NaN
10  Substitution      85         NaN         NaN      Home         NaN
11  Substitution      85         NaN         NaN      Home         NaN
12          Card      87         NaN         NaN      Home      E. Can
13           NaN      90         NaN         NaN       NaN         NaN
14           NaN      90         NaN         NaN       NaN         NaN
15           NaN      90         NaN         NaN       NaN         NaN
16          Goal      90      E. Can           -      Home         NaN

   Home Reason Home Card Type Home Player In Home Player Out    Away Event  \
0          NaN            NaN            NaN             NaN          Goal
1          NaN            NaN            NaN             NaN           NaN
2          NaN            NaN     J. Gittens      K. Adeyemi           NaN
3          NaN            NaN      F. Nmecha         M. Reus           NaN
4          NaN            NaN            NaN             NaN  Substitution
5          NaN            NaN     Y. Moukoko     N. Füllkrug           NaN
6          NaN            NaN            NaN             NaN  Substitution
7          NaN            NaN            NaN             NaN  Substitution
8          NaN            NaN            NaN             NaN          Card
9          NaN            NaN            NaN             NaN           NaN
10         NaN            NaN       S. Özcan       J. Brandt           NaN
11         NaN            NaN  R. Bensebaini      I. Maatsen           NaN
12        Foul         yellow            NaN             NaN           NaN
13         NaN            NaN            NaN             NaN          Card
14         NaN            NaN            NaN             NaN  Substitution
15         NaN            NaN            NaN             NaN  Substitution
16         NaN            NaN            NaN             NaN           NaN

   Away Player Away Reason Away Card Type Away Team Away Player In  \
0          NaN         NaN            NaN      Away            NaN
1          NaN         NaN            NaN       NaN            NaN
2          NaN         NaN            NaN       NaN            NaN
3          NaN         NaN            NaN       NaN            NaN
4          NaN         NaN            NaN      Away      F. Chaïbi
5          NaN         NaN            NaN       NaN            NaN
6          NaN         NaN            NaN      Away     H. Ekitiké
7          NaN         NaN            NaN      Away        A. Buta
8      A. Buta        Foul         yellow      Away            NaN
9          NaN         NaN            NaN       NaN            NaN
10         NaN         NaN            NaN       NaN            NaN
11         NaN         NaN            NaN       NaN            NaN
12         NaN         NaN            NaN       NaN            NaN
13     R. Koch        Foul         yellow      Away            NaN
14         NaN         NaN            NaN      Away      M. Hasebe
15         NaN         NaN            NaN      Away    T. Chandler
16         NaN         NaN            NaN       NaN            NaN

   Away Player Out Away Scorer Away Assist
0              NaN    M. Götze           -
1              NaN         NaN         NaN
2              NaN         NaN         NaN
3              NaN         NaN         NaN
4     J. D. Ebimbe         NaN         NaN
5              NaN         NaN         NaN
6         M. Götze         NaN         NaN
7        A. Knauff         NaN         NaN
8              NaN         NaN         NaN
9              NaN         NaN         NaN
10             NaN         NaN         NaN
11             NaN         NaN         NaN
12             NaN         NaN         NaN
13             NaN         NaN         NaN
14       E. Skhiri         NaN         NaN
15            Tuta         NaN         NaN
16             NaN         NaN         NaN
      Home Event  Minute Home Scorer Home Assist Home Team Home Player In  \
0            NaN      19         NaN         NaN       NaN            NaN
1            NaN      33         NaN         NaN       NaN            NaN
2   Substitution      58         NaN         NaN      Home        A. Adli
3            NaN      58         NaN         NaN       NaN            NaN
4   Substitution      71         NaN         NaN      Home    B. Iglesias
5            NaN      73         NaN         NaN       NaN            NaN
6            NaN      73         NaN         NaN       NaN            NaN
7            NaN      78         NaN         NaN       NaN            NaN
8   Substitution      86         NaN         NaN      Home    J. Stanišić
9   Substitution      86         NaN         NaN      Home       N. Tella
10          Goal      88  R. Andrich      J. Tah      Home            NaN
11          Goal      90   P. Schick    N. Tella      Home            NaN

   Home Player Out    Away Event Away Player In Away Player Out Away Team  \
0              NaN          Card            NaN             NaN      Away
1              NaN          Goal            NaN             NaN      Away
2       J. Hofmann           NaN            NaN             NaN       NaN
3              NaN  Substitution      G. Prömel     A. Kramarić      Away
4      P. Hincapié           NaN            NaN             NaN       NaN
5              NaN  Substitution       I. Bebou        M. Beier      Away
6              NaN  Substitution      D. Geiger      U. Tohumcu      Away
7              NaN  Substitution      M. Bülter     W. Weghorst      Away
8       E. Tapsoba           NaN            NaN             NaN       NaN
9      J. Frimpong           NaN            NaN             NaN       NaN
10             NaN           NaN            NaN             NaN       NaN
11             NaN           NaN            NaN             NaN       NaN

   Away Scorer  Away Assist Away Player Away Reason Away Card Type
0          NaN          NaN  T. Drexler        Foul         yellow
1     M. Beier  W. Weghorst         NaN         NaN            NaN
2          NaN          NaN         NaN         NaN            NaN
3          NaN          NaN         NaN         NaN            NaN
4          NaN          NaN         NaN         NaN            NaN
5          NaN          NaN         NaN         NaN            NaN
6          NaN          NaN         NaN         NaN            NaN
7          NaN          NaN         NaN         NaN            NaN
8          NaN          NaN         NaN         NaN            NaN
9          NaN          NaN         NaN         NaN            NaN
10         NaN          NaN         NaN         NaN            NaN
11         NaN          NaN         NaN         NaN            NaN
      Home Event  Minute Home Player In Home Player Out Home Team Home Player  \
0            NaN       7            NaN             NaN       NaN         NaN
1           Card      32            NaN             NaN      Home  K. Itakura
2            NaN      47            NaN             NaN       NaN         NaN
3            NaN      57            NaN             NaN       NaN         NaN
4   Substitution      62     N. Ngoumou         R. Hack      Home         NaN
5   Substitution      62        A. Pléa      F. Neuhaus      Home         NaN
6   Substitution      62    T. Čvančara   J. Siebatcheu      Home         NaN
7   Substitution      70       M. Wöber       N. Elvedi      Home         NaN
8   Substitution      75      S. Lainer       J. Scally      Home         NaN
9            NaN      75            NaN             NaN       NaN         NaN
10           NaN      75            NaN             NaN       NaN         NaN
11           NaN      90            NaN             NaN       NaN         NaN
12           NaN      90            NaN             NaN       NaN         NaN
13           NaN      90            NaN             NaN       NaN         NaN

   Home Reason Home Card Type    Away Event Away Player In Away Player Out  \
0          NaN            NaN          Goal            NaN             NaN
1         Foul         yellow           NaN            NaN             NaN
2          NaN            NaN          Goal            NaN             NaN
3          NaN            NaN          Goal            NaN             NaN
4          NaN            NaN           NaN            NaN             NaN
5          NaN            NaN           NaN            NaN             NaN
6          NaN            NaN           NaN            NaN             NaN
7          NaN            NaN           NaN            NaN             NaN
8          NaN            NaN           NaN            NaN             NaN
9          NaN            NaN  Substitution       V. Grifo  M. Gregoritsch
10         NaN            NaN  Substitution      A. Szalai       Y. Keitel
11         NaN            NaN  Substitution     F. Muslija       N. Höfler
12         NaN            NaN  Substitution     J. Makengo       C. Günter
13         NaN            NaN  Substitution       C. Adamu        L. Höler

   Away Team     Away Scorer   Away Assist
0       Away  M. Gregoritsch             -
1        NaN             NaN           NaN
2       Away         M. Röhl             -
3       Away         R. Doan  M. Eggestein
4        NaN             NaN           NaN
5        NaN             NaN           NaN
6        NaN             NaN           NaN
7        NaN             NaN           NaN
8        NaN             NaN           NaN
9       Away             NaN           NaN
10      Away             NaN           NaN
11      Away             NaN           NaN
12      Away             NaN           NaN
13      Away             NaN           NaN
      Home Event  Minute Home Player In Home Player Out Home Team  \
0           Card      24            NaN             NaN      Home
1           Card      38            NaN             NaN      Home
2   Substitution      46         P. Max     N. Nkounkou      Home
3            NaN      61            NaN             NaN       NaN
4            NaN      65            NaN             NaN       NaN
5            NaN      65            NaN             NaN       NaN
6            NaN      65            NaN             NaN       NaN
7   Substitution      71      F. Chaïbi      H. Ekitiké      Home
8   Substitution      79      J. Bahoya       A. Knauff      Home
9            NaN      82            NaN             NaN       NaN
10           NaN      89            NaN             NaN       NaN
11  Substitution      90    T. Chandler    J. D. Ebimbe      Home
12          Card      90            NaN             NaN      Home

    Home Player Home Reason Home Card Type    Away Event Away Player In  \
0    H. Ekitiké        Foul         yellow           NaN            NaN
1   N. Nkounkou    Argument         yellow           NaN            NaN
2           NaN         NaN            NaN           NaN            NaN
3           NaN         NaN            NaN          Card            NaN
4           NaN         NaN            NaN  Substitution    A. Laïdouni
5           NaN         NaN            NaN  Substitution  B. Hollerbach
6           NaN         NaN            NaN  Substitution     K. Volland
7           NaN         NaN            NaN           NaN            NaN
8           NaN         NaN            NaN           NaN            NaN
9           NaN         NaN            NaN  Substitution   J. Juranović
10          NaN         NaN            NaN  Substitution  J. Roussillon
11          NaN         NaN            NaN           NaN            NaN
12     W. Pacho        Foul         yellow           NaN            NaN

   Away Player Out Away Team Away Player   Away Reason Away Card Type
0              NaN       NaN         NaN           NaN            NaN
1              NaN       NaN         NaN           NaN            NaN
2              NaN       NaN         NaN           NaN            NaN
3              NaN      Away    D. Leite  Time wasting         yellow
4      B. Aaronson      Away         NaN           NaN            NaN
5   M. K. Sorensen      Away         NaN           NaN            NaN
6     Y. Vertessen      Away         NaN           NaN            NaN
7              NaN       NaN         NaN           NaN            NaN
8              NaN       NaN         NaN           NaN            NaN
9       C. Trimmel      Away         NaN           NaN            NaN
10       R. Gosens      Away         NaN           NaN            NaN
11             NaN       NaN         NaN           NaN            NaN
12             NaN       NaN         NaN           NaN            NaN
      Home Event  Minute Home Player In Home Player Out Home Team Home Player  \
0            NaN      20            NaN             NaN       NaN         NaN
1            NaN      27            NaN             NaN       NaN         NaN
2            NaN      34            NaN             NaN       NaN         NaN
3            NaN      56            NaN             NaN       NaN         NaN
4            NaN      56            NaN             NaN       NaN         NaN
5            NaN      56            NaN             NaN       NaN         NaN
6           Card      67            NaN             NaN      Home   C. Lukeba
7   Substitution      68       B. Šeško       L. Openda      Home         NaN
8   Substitution      68     Y. Poulsen  C. Baumgartner      Home         NaN
9            NaN      70            NaN             NaN       NaN         NaN
10           NaN      79            NaN             NaN       NaN         NaN
11           NaN      81            NaN             NaN       NaN         NaN
12  Substitution      82     M. Simakan        K. Kampl      Home         NaN
13  Substitution      82     N. Seiwald     B. Henrichs      Home         NaN
14  Substitution      86       E. Elmas      Y. Poulsen      Home         NaN
15          Card      86            NaN             NaN      Home   X. Simons

   Home Reason Home Card Type    Away Event Away Player In  Away Player Out  \
0          NaN            NaN          Card            NaN              NaN
1          NaN            NaN          Card            NaN              NaN
2          NaN            NaN          Card            NaN              NaN
3          NaN            NaN  Substitution      S. Widmer          A. Caci
4          NaN            NaN  Substitution       B. Gruda       L. Ajorque
5          NaN            NaN  Substitution         J. Lee       K. Onisiwo
6         Foul         yellow           NaN            NaN              NaN
7          NaN            NaN           NaN            NaN              NaN
8          NaN            NaN           NaN            NaN              NaN
9          NaN            NaN          Card            NaN              NaN
10         NaN            NaN          Card            NaN              NaN
11         NaN            NaN  Substitution   E. Fernandes  A. Hanche-Olsen
12         NaN            NaN           NaN            NaN              NaN
13         NaN            NaN           NaN            NaN              NaN
14         NaN            NaN           NaN            NaN              NaN
15        Foul         yellow           NaN            NaN              NaN

   Away Team      Away Player         Away Reason Away Card Type
0       Away          A. Caci                Foul         yellow
1       Away         P. Mwene                Foul         yellow
2       Away         N. Amiri                Foul         yellow
3       Away              NaN                 NaN            NaN
4       Away              NaN                 NaN            NaN
5       Away              NaN                 NaN            NaN
6        NaN              NaN                 NaN            NaN

## In code below, we saved all data  frames for each individiual match into one list

In [14]:
dataframes_list = []

# Iterate through all incidents and store the resulting dataframes in the list
for i in range(306):
    events = extract_events(all_incidents[i])
    df = create_dataframe(events)
    dataframes_list.append(df)

## Here we create games list, where we put a name to each individual match (this will be handy in further functions)

In [15]:
games_names = [ "BremenXBayern", "LeverkusenXLeipzig", "AugsburgXMgladbach", "HoffenheimXFreiburg", "StuttgartXBochum", "WolfsburgXHeidenheim", "DortmundXKoln", "Union_BerlinXMainz", "FrankfurtXDarmstadt",
    "LeipzigXStuttgart", "HeidenheimXHoffenheim", "KolnXWolfsburg", "DarmstadtXUnion_Berlin", "FreiburgXBremen", "BochumXDortmund", "MgladbachXLeverkusen", "MainzXFrankfurt", "BayernXAugsburg",
    "DortmundXHeidenheim", "LeverkusenXDarmstadt", "AugsburgXBochum", "BremenXMainz", "HoffenheimXWolfsburg", "StuttgartXFreiburg", "MgladbachXBayern", "FrankfurtXKoln", "Union_BerlinXLeipzig",
    "BayernXLeverkusen", "KolnXHoffenheim", "MainzXStuttgart", "LeipzigXAugsburg", "FreiburgXDortmund", "WolfsburgXUnion_Berlin", "BochumXFrankfurt", "HeidenheimXBremen", "DarmstadtXMgladbach",
    "StuttgartXDarmstadt","Union_BerlinXHoffenheim","DortmundXWolfsburg","MgladbachXLeipzig","AugsburgXMainz","BayernXBochum","BremenXKoln","LeverkusenXHeidenheim","FrankfurtXFreiburg",
    "HoffenheimXDortmund", "HeidenheimXUnion_Berlin", "KolnXStuttgart", "MainzXLeverkusen", "BochumXMgladbach", "WolfsburgXFrankfurt", "LeipzigXBayern", "DarmstadtXBremen", "FreiburgXAugsburg",
    "MgladbachXMainz", "DortmundXUnion_Berlin", "AugsburgXDarmstadt", "LeipzigXBochum", "StuttgartXWolfsburg", "BremenXHoffenheim", "LeverkusenXKoln", "BayernXFreiburg", "FrankfurtXHeidenheim",
    "DortmundXBremen", "Union_BerlinXStuttgart", "DarmstadtXLeipzig", "FreiburgXBochum", "HoffenheimXFrankfurt", "WolfsburgXLeverkusen", "MainzXBayern", "KolnXMgladbach", "HeidenheimXAugsburg",
    "BochumXMainz", "MgladbachXHeidenheim", "AugsburgXWolfsburg", "BayernXDarmstadt", "BremenXUnion_Berlin", "StuttgartXHoffenheim", "LeipzigXKoln", "FrankfurtXDortmund", "LeverkusenXFreiburg",
    "DarmstadtXBochum",  "KolnXAugsburg", "Union_BerlinXFrankfurt", "MainzXLeipzig",  "FreiburgXMgladbach",  "HoffenheimXLeverkusen",  "DortmundXBayern",  "WolfsburgXBremen",  "HeidenheimXStuttgart",
    "MgladbachXWolfsburg","DarmstadtXMainz", "AugsburgXHoffenheim",  "BayernXHeidenheim","StuttgartXDortmund","BochumXKoln","LeverkusenXUnion_Berlin","BremenXFrankfurt","LeipzigXFreiburg",
    "KolnXBayern","Union_BerlinXAugsburg","DortmundXMgladbach","FreiburgXDarmstadt","BremenXLeverkusen","WolfsburgXLeipzig","FrankfurtXStuttgart","HeidenheimXBochum","HoffenheimXMainz",
    "DarmstadtXKoln", "MgladbachXHoffenheim", "LeipzigXHeidenheim", "BochumXWolfsburg", "StuttgartXBremen", "MainzXFreiburg", "LeverkusenXDortmund", "AugsburgXFrankfurt", "BayernXUnion_Berlin",
    "HoffenheimXBochum", "HeidenheimXDarmstadt", "Union_BerlinXMgladbach", "FrankfurtXBayern", "BremenXAugsburg", "WolfsburgXFreiburg", "DortmundXLeipzig", "StuttgartXLeverkusen", "KolnXMainz",
    "MgladbachXBremen", "MainzXHeidenheim", "DarmstadtXWolfsburg", "AugsburgXDortmund", "BochumXUnion_Berlin", "LeipzigXHoffenheim", "FreiburgXKoln", "LeverkusenXFrankfurt","BayernXStuttgart",
    "BremenXLeipzig","DortmundXMainz","HoffenheimXDarmstadt","Union_BerlinXKoln","HeidenheimXFreiburg","LeverkusenXBochum","FrankfurtXMgladbach","StuttgartXAugsburg","WolfsburgXBayern",
    "BayernXHoffenheim","KolnXHeidenheim","MainzXWolfsburg","AugsburgXLeverkusen","LeipzigXFrankfurt","FreiburgXUnion_Berlin","DarmstadtXDortmund","BochumXBremen","MgladbachXStuttgart",
    "HeidenheimXWolfsburg","KolnXDortmund","DarmstadtXFrankfurt","FreiburgXHoffenheim","BochumXStuttgart","LeipzigXLeverkusen","BayernXBremen","MgladbachXAugsburg","MainzXUnion_Berlin",
    "FrankfurtXMainz","AugsburgXBayern","BremenXFreiburg","HoffenheimXHeidenheim","StuttgartXLeipzig","WolfsburgXKoln","LeverkusenXMgladbach","Union_BerlinXDarmstadt","DortmundXBochum",
    "HeidenheimXDortmund","MainzXBremen","DarmstadtXLeverkusen","BayernXMgladbach","FreiburgXStuttgart","BochumXAugsburg","KolnXFrankfurt","WolfsburgXHoffenheim","LeipzigXUnion_Berlin",
    "DortmundXFreiburg","Union_BerlinXWolfsburg","MgladbachXDarmstadt","FrankfurtXBochum","AugsburgXLeipzig","BremenXHeidenheim","LeverkusenXBayern","StuttgartXMainz","HoffenheimXKoln",
    "KolnXBremen", "HeidenheimXLeverkusen", "MainzXAugsburg", "DarmstadtXStuttgart", "HoffenheimXUnion_Berlin", "WolfsburgXDortmund", "LeipzigXMgladbach", "FreiburgXFrankfurt", "BochumXBayern",
    "LeverkusenXMainz", "Union_BerlinXHeidenheim", "MgladbachXBochum", "BremenXDarmstadt", "StuttgartXKoln", "BayernXLeipzig", "FrankfurtXWolfsburg", "DortmundXHoffenheim", "AugsburgXFreiburg",
    "FreiburgXBayern", "HeidenheimXFrankfurt", "Union_BerlinXDortmund", "MainzXMgladbach", "DarmstadtXAugsburg", "BochumXLeipzig", "WolfsburgXStuttgart", "KolnXLeverkusen", "HoffenheimXBremen",
    "StuttgartXUnion_Berlin", "MgladbachXKoln", "AugsburgXHeidenheim","BayernXMainz","LeipzigXDarmstadt","BremenXDortmund","BochumXFreiburg","FrankfurtXHoffenheim","LeverkusenXWolfsburg",
    "KolnXLeipzig","HeidenheimXMgladbach","Union_BerlinXBremen","MainzXBochum","DarmstadtXBayern","WolfsburgXAugsburg","HoffenheimXStuttgart","FreiburgXLeverkusen","DortmundXFrankfurt",
    "LeverkusenXHoffenheim","MgladbachXFreiburg","FrankfurtXUnion_Berlin","LeipzigXMainz","BremenXWolfsburg","BayernXDortmund","AugsburgXKoln","StuttgartXHeidenheim","BochumXDarmstadt",
    "FrankfurtXBremen", "HeidenheimXBayern", "KolnXBochum", "Union_BerlinXLeverkusen","MainzXDarmstadt","FreiburgXLeipzig","DortmundXStuttgart","HoffenheimXAugsburg","WolfsburgXMgladbach",
    "AugsburgXUnion_Berlin","MainzXHoffenheim", "MgladbachXDortmund", "BayernXKoln", "LeipzigXWolfsburg", "BochumXHeidenheim", "StuttgartXFrankfurt", "DarmstadtXFreiburg", "LeverkusenXBremen",
    "FrankfurtXAugsburg", "HeidenheimXLeipzig", "KolnXDarmstadt", "HoffenheimXMgladbach", "WolfsburgXBochum", "Union_BerlinXBayern", "BremenXStuttgart", "DortmundXLeverkusen", "FreiburgXMainz",
    "BochumXHoffenheim", "AugsburgXBremen", "BayernXFrankfurt", "LeipzigXDortmund", "FreiburgXWolfsburg", "LeverkusenXStuttgart", "MgladbachXUnion_Berlin", "MainzXKoln", "DarmstadtXHeidenheim",
    "HoffenheimXLeipzig", "DortmundXAugsburg", "BremenXMgladbach", "StuttgartXBayern", "WolfsburgXDarmstadt", "KolnXFreiburg", "Union_BerlinXBochum", "FrankfurtXLeverkusen", "HeidenheimXMainz",
    "AugsburgXStuttgart", "KolnXUnion_Berlin","MgladbachXFrankfurt", "LeipzigXBremen","FreiburgXHeidenheim", "MainzXDortmund", "DarmstadtXHoffenheim", "BayernXWolfsburg","BochumXLeverkusen",
    "HeidenheimXKoln","Union_BerlinXFreiburg","LeverkusenXAugsburg","DortmundXDarmstadt","FrankfurtXLeipzig","BremenXBochum","HoffenheimXBayern","StuttgartXMgladbach","WolfsburgXMainz"
]

# Dynamically create variables in globals
for i, game in enumerate(games_names):
    globals()[game] = dataframes_list[i]

# Now, safely create games_list
games_list = []
for game in games_names:
    if game in globals():
        games_list.append(globals()[game])
    else:
        raise NameError(f"Variable '{game}' not found in globals.")

# Add names to dataframes
for i, df in enumerate(games_list):
    df.name = games_names[i]

## Now, the most important part, we will create a function which will calculate a league table based on certian conditions set by user

In [47]:
import pandas as pd

def calculate_league_table():
    # Prompt user for input
    minute_from = int(input("From which minute do you want goals to count? "))
    minute_to = int(input("To which minute do you want goals to count? "))

    exclude_top_goalscorers = input("Do goals from top scorers count? (Yes/No): ").strip().lower() == 'no'
    exclude_most_valuable_players = input("Do goals from most valuable players count? (Yes/No): ").strip().lower() == 'no'
    exclude_captains = input("Do goals from captains count? (Yes/No): ").strip().lower() == 'no'
    exclude_substituted_in_scorers = input("Do goals from substituted players count? (Yes/No): ").strip().lower() == 'no'

    top_goalscorers = pd.Series(["H. Kane", "V. O. Boniface", "B. Šeško", "S. Guirassy", "M. Beier", "E. Demirović",
                                "D. Malen", "M. Ducksch", "O. Marmoush", "J. Wind", "T. Kleindienst",
                                "R. Hack", "J. Burkardt", "K. Stöger", "T. Skarke", "V. Grifo", "R. Gosens", "D. Selke"])
    top_goalscorers = pd.DataFrame(top_goalscorers, columns=['goalscorers'])

    most_valuable_players = pd.Series(["J. Musiala", "F. Wirtz", "S. Guirassy", "X. Simons", "J. Brnadt", "R. K. Muani",
                                       "M. Beier", "P. Wanner", "N. Füllkrug", "R. Doan", "E. Demirović", "L. Majer",
                                       "B. Gruda", "M. Koné", "D. Doekhi", "P. Osterhage", "J. Chabot", "T. Skarke"])
    most_valuable_players = pd.DataFrame(most_valuable_players, columns=['players'])

    captains = pd.Series(["M. Neuer", "E. Can", "W. Orbán", "C. Trimmel", "C. Günter","L. Hradecky","S. Rode",
                          "M. Arnold", "S. Widmer","J. Omlin","F. Kainz", "O. Baumann","M. Friedl","A. Losilla","E. Demirović",
                          "W. Anton", "P. Mainka", "F. Holland"])
    captains = pd.DataFrame(captains, columns=['captains'])

    league_table = {}

    for df in games_list:
        try:
            # Extract home and away team names from DataFrame name
            game_name = df.name
            if 'X' not in game_name:
                raise ValueError(f"Game name '{game_name}' is not in the correct format 'HomeTeamXAwayTeam'")

            home_team, away_team = game_name.split('X')

            # Initialize missing columns if they don't exist
            necessary_columns = ['Minute', 'Home Event', 'Away Event']
            if exclude_substituted_in_scorers:
                necessary_columns += ['Home Player In', 'Away Player In']

            for col in necessary_columns:
                if col not in df.columns:
                    df[col] = None

            # Fill missing values in scorer columns
            df['Home Scorer'] = df.get('Home Scorer', pd.Series([None] * len(df)))
            df['Away Scorer'] = df.get('Away Scorer', pd.Series([None] * len(df)))

            # Filter events based on minute range
            df_filtered = df[(df['Minute'] >= minute_from) & (df['Minute'] <= minute_to)]

            # Initialize teams in the league table
            if home_team not in league_table:
                league_table[home_team] = {'points': 0, 'goals_scored': 0, 'goals_conceded': 0}
            if away_team not in league_table:
                league_table[away_team] = {'points': 0, 'goals_scored': 0, 'goals_conceded': 0}

            # Apply conditions for excluding goals
            if exclude_top_goalscorers:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(top_goalscorers['goalscorers']) &
                                          ~df_filtered['Away Scorer'].isin(top_goalscorers['goalscorers'])]

            if exclude_most_valuable_players:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(most_valuable_players['players']) &
                                          ~df_filtered['Away Scorer'].isin(most_valuable_players['players'])]

            if exclude_substituted_in_scorers:
                home_subs_in = df_filtered['Home Player In'].dropna().unique()
                away_subs_in = df_filtered['Away Player In'].dropna().unique()
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(home_subs_in) &
                                          ~df_filtered['Away Scorer'].isin(away_subs_in)]

            if exclude_captains:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(captains['captains']) &
                                          ~df_filtered['Away Scorer'].isin(captains['captains'])]

            # Calculate goals and update league table
            home_goals_count = df_filtered[df_filtered['Home Event'] == 'Goal'].shape[0]
            away_goals_count = df_filtered[df_filtered['Away Event'] == 'Goal'].shape[0]

            league_table[home_team]['goals_scored'] += home_goals_count
            league_table[home_team]['goals_conceded'] += away_goals_count
            league_table[away_team]['goals_scored'] += away_goals_count
            league_table[away_team]['goals_conceded'] += home_goals_count

            if home_goals_count > away_goals_count:
                league_table[home_team]['points'] += 3
            elif home_goals_count < away_goals_count:
                league_table[away_team]['points'] += 3
            else:
                league_table[home_team]['points'] += 1
                league_table[away_team]['points'] += 1

        except Exception as e:
            print(f"Error processing dataframe {df.name}: {e}")

    league_df = pd.DataFrame.from_dict(league_table, orient='index')
    league_df['goal_difference'] = league_df['goals_scored'] - league_df['goals_conceded']
    league_df = league_df.sort_values(by=['points', 'goal_difference', 'goals_scored'], ascending=False)

    return league_df

## This is the final function

In [48]:
calculate_league_table()Y

From which minute do you want goals to count? 1
To which minute do you want goals to count? 90
Do goals from top scorers count? (Yes/No): Yes
Do goals from most valuable players count? (Yes/No): Yes
Do goals from captains count? (Yes/No): Yes
Do goals from substituted players count? (Yes/No): Yes

              points  goals_scored  goals_conceded  goal_difference
Leverkusen        90            89              24               65
Stuttgart         73            78              39               39
Bayern            72            94              45               49
Leipzig           65            77              39               38
Dortmund          63            68              43               25
Frankfurt         47            51              50                1
Hoffenheim        46            66              66                0
Heidenheim        42            50              55               -5
Bremen            42            48              54               -6
Freiburg          42            45              58              -13
Augsburg          39            50              60              -10
Wolfsburg         37            41              56              -15
Mainz             35            39              51              -12
Mgladbach         34            56              67              -11
Union_Berlin      33            33              58              -25
Bochum            33            42              74              -32
Koln              27            28              60              -32
Darmstadt         17            30              86              -56

In [ ]:
table_without_conditions = ["Leverkusen","Stuttgart","Bayern","Leipzig","Dortmund","Frankfurt","Hoffenheim","Heidenheim","Bremen","Freiburg","Augsburg","Wolfsburg","Mainz","Mgladbach","Union_Berlin","Bochum","Koln","Darmstadt"]

## ........................................ODSUD DOLU NIC ..................................

In [45]:
import pandas as pd

def calculate_league_table():
    # Prompt user for input
    minute_from = int(input("From which minute do you want goals to count? "))
    minute_to = int(input("To which minute do you want goals to count? "))

    exclude_top_goalscorers = input("Do goals from top scorers count? (Yes/No): ").strip().lower() == 'no'
    exclude_most_valuable_players = input("Do goals from most valuable players count? (Yes/No): ").strip().lower() == 'no'
    exclude_captains = input("Do goals from captains count? (Yes/No): ").strip().lower() == 'no'
    exclude_substituted_in_scorers = input("Do goals from substituted players count? (Yes/No): ").strip().lower() == 'no'

    top_goalscorers = pd.Series(["H. Kane", "V. O. Boniface", "B. Šeško", "S. Guirassy", "M. Beier", "E. Demirović",
                                "D. Malen", "M. Ducksch", "O. Marmoush", "J. Wind", "T. Kleindienst",
                                "R. Hack", "J. Burkardt", "K. Stöger", "T. Skarke", "V. Grifo", "R. Gosens", "D. Selke"])
    top_goalscorers = pd.DataFrame(top_goalscorers, columns=['goalscorers'])

    most_valuable_players = pd.Series(["J. Musiala", "F. Wirtz", "S. Guirassy", "X. Simons", "J. Brnadt", "R. K. Muani",
                                       "M. Beier", "P. Wanner", "N. Füllkrug", "R. Doan", "E. Demirović", "L. Majer",
                                       "B. Gruda", "M. Koné", "D. Doekhi", "P. Osterhage", "J. Chabot", "T. Skarke"])
    most_valuable_players = pd.DataFrame(most_valuable_players, columns=['players'])

    captains = pd.Series(["M. Neuer", "E. Can", "W. Orbán", "C. Trimmel", "C. Günter","L. Hradecky","S. Rode",
                          "M. Arnold", "S. Widmer","J. Omlin","F. Kainz", "O. Baumann","M. Friedl","A. Losilla","E. Demirović",
                          "W. Anton", "P. Mainka", "F. Holland"])
    captains = pd.DataFrame(captains, columns=['captains'])

    league_table = {}

    for df in games_list:
        try:
            # Extract home and away team names from DataFrame name
            game_name = df.name
            if 'X' not in game_name:
                raise ValueError(f"Game name '{game_name}' is not in the correct format 'HomeTeamXAwayTeam'")

            home_team, away_team = game_name.split('X')

            # Initialize missing columns if they don't exist
            necessary_columns = ['Minute', 'Home Event', 'Away Event']
            if exclude_substituted_in_scorers:
                necessary_columns += ['Home Player In', 'Away Player In']

            for col in necessary_columns:
                if col not in df.columns:
                    df[col] = None

            # Fill missing values in scorer columns
            df['Home Scorer'] = df.get('Home Scorer', pd.Series([None] * len(df)))
            df['Away Scorer'] = df.get('Away Scorer', pd.Series([None] * len(df)))

            # Filter events based on minute range
            df_filtered = df[(df['Minute'] >= minute_from) & (df['Minute'] <= minute_to)]

            # Initialize teams in the league table
            if home_team not in league_table:
                league_table[home_team] = {'points': 0, 'goals_scored': 0, 'goals_conceded': 0}
            if away_team not in league_table:
                league_table[away_team] = {'points': 0, 'goals_scored': 0, 'goals_conceded': 0}

            # Apply conditions for excluding goals
            if exclude_top_goalscorers:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(top_goalscorers['goalscorers']) &
                                          ~df_filtered['Away Scorer'].isin(top_goalscorers['goalscorers'])]

            if exclude_most_valuable_players:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(most_valuable_players['players']) &
                                          ~df_filtered['Away Scorer'].isin(most_valuable_players['players'])]

            if exclude_substituted_in_scorers:
                home_subs_in = df_filtered['Home Player In'].dropna().unique()
                away_subs_in = df_filtered['Away Player In'].dropna().unique()
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(home_subs_in) &
                                          ~df_filtered['Away Scorer'].isin(away_subs_in)]

            if exclude_captains:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(captains['captains']) &
                                          ~df_filtered['Away Scorer'].isin(captains['captains'])]

            # Calculate goals and update league table
            home_goals_count = df_filtered[df_filtered['Home Event'] == 'Goal'].shape[0]
            away_goals_count = df_filtered[df_filtered['Away Event'] == 'Goal'].shape[0]

            league_table[home_team]['goals_scored'] += home_goals_count
            league_table[home_team]['goals_conceded'] += away_goals_count
            league_table[away_team]['goals_scored'] += away_goals_count
            league_table[away_team]['goals_conceded'] += home_goals_count

            if home_goals_count > away_goals_count:
                league_table[home_team]['points'] += 3
            elif home_goals_count < away_goals_count:
                league_table[away_team]['points'] += 3
            else:
                league_table[home_team]['points'] += 1
                league_table[away_team]['points'] += 1

        except Exception as e:
            print(f"Error processing dataframe {df.name}: {e}")

    league_df = pd.DataFrame.from_dict(league_table, orient='index')
    league_df['goal_difference'] = league_df['goals_scored'] - league_df['goals_conceded']
    league_df = league_df.sort_values(by=['points', 'goal_difference', 'goals_scored'], ascending=False)

    # return league_df

# Add rank with conditions
    league_df['Rank_with_conditions'] = league_df.index + 1  # Adding 1 to make it 1-based index

    # Known final positions
    table_without_conditions = [
        "Leverkusen", "Stuttgart", "Bayern", "Leipzig", "Dortmund", "Frankfurt", "Hoffenheim",
        "Heidenheim", "Bremen", "Freiburg", "Augsburg", "Wolfsburg", "Mainz", "Mgladbach",
        "Union_Berlin", "Bochum", "Koln", "Darmstadt"
    ]

    # Create DataFrame for known final positions
    known_positions = pd.DataFrame(table_without_conditions, columns=['Team'])
    known_positions['Rank_without_conditions'] = known_positions.index + 1  # Adding 1 to make it 1-based index

    # Merge calculated league table with known final positions
    merged_df = pd.merge(league_df, known_positions, on='Team', how='left')

    # Calculate position differences
    merged_df['Position_difference'] = merged_df['Rank_without_conditions'] - merged_df['Rank_with_conditions']

    # Return final DataFrame including the position difference
    return merged_df[['Team', 'points', 'goals_scored', 'goals_conceded', 'goal_difference',
                      "Rank_without_conditions", "Rank_with_conditions", 'Position_difference']]

In [46]:
calculate_league_table()

From which minute do you want goals to count? 1
To which minute do you want goals to count? 90
Do goals from top scorers count? (Yes/No): Yes
Do goals from most valuable players count? (Yes/No): Yes
Do goals from captains count? (Yes/No): Yes
Do goals from substituted players count? (Yes/No): Yes

TypeError: can only concatenate str (not "int") to str

In [ ]:
assisters = pd.Series(["A. Grimaldo","J. Beste","J. Brandt","L. Sané","X. Simmons","D. Undav","E. Demirovic","F. Honorat","K. Stöger","M. Ducksch","V. Grifo","J. Wind","M. Weiser","O. Marmoush","F. Grillitsch","F. Kainz","E. Dinkçi","K. Volland"])
top_assisters = pd.DataFrame(assisters, columns=['assisters'])
print(top_assisters)

In [76]:
import pandas as pd

def calculate_league_table():
    # Prompt user for input
    minute_from = int(input("From which minute do you want goals to count? "))
    minute_to = int(input("To which minute do you want goals to count? "))

    exclude_top_goalscorers = input("Do goals from top scorers count? (Yes/No): ").strip().lower() == 'no'
    exclude_most_valuable_players = input("Do goals from most valuable players count? (Yes/No): ").strip().lower() == 'no'
    exclude_captains = input("Do goals from captains count? (Yes/No): ").strip().lower() == 'no'
    exclude_substituted_in_scorers = input("Do goals from substituted players count? (Yes/No): ").strip().lower() == 'no'

    # List of topscorers, most valuable players, and captains of each team
    top_goalscorers = pd.Series(["H. Kane","V. O. Boniface","B. Šeško","S. Guirassy","M. Beier","E. Demirović",
                                "D. Malen","M. Ducksch", "O. Marmoush", "J. Wind", "T. Kleindienst",
                                "R. Hack", "J. Burkardt","K. Stöger", "T. Skarke","V. Grifo","R. Gosens","D. Selke"])
    top_goalscorers = pd.DataFrame(top_goalscorers, columns=['goalscorers'])

    most_valuable_players = pd.Series(["J. Musiala", "F. Wirtz", "S. Guirassy", "X. Simons", "J. Brnadt", "R. K. Muani",
                                       "M. Beier",  "P. Wanner", "N. Füllkrug","R. Doan", "E. Demirović", "L. Majer",
                                       "B. Gruda", "M. Koné", "D. Doekhi","P. Osterhage","J. Chabot", "T. Skarke"])
    most_valuable_players = pd.DataFrame(most_valuable_players, columns=['players'])

    captains = pd.Series(["M. Neuer", "E. Can", "W. Orbán", "C. Trimmel", "C. Günter","L. Hradecky","S. Rode",
                          "M. Arnold", "S. Widmer","J. Omlin","F. Kainz", "O. Baumann","M. Friedl","A. Losilla","E. Demirović",
                          "W. Anton", "P. Mainka", "F. Holland"])
    captains = pd.DataFrame(captains, columns=['captains'])

    # Initialize league table
    league_table = {}

    for df in games_list:
        try:
            # Extract home and away team names from DataFrame name
            game_name = df.name
            if 'X' not in game_name:
                raise ValueError(f"Game name '{game_name}' is not in the correct format 'HomeTeamXAwayTeam'")

            home_team, away_team = game_name.split('X')

            # Ensure necessary columns exist
            necessary_columns = ['Minute', 'Home Event', 'Away Event']
            if exclude_substituted_in_scorers:
                necessary_columns += ['Home Player In', 'Away Player In']

            missing_columns = [col for col in necessary_columns if col not in df.columns]

            if missing_columns:
                print(f"Missing columns: {missing_columns}. Assigning default values.")
                for col in missing_columns:
                    df[col] = None

            # Filter events to include only those within the specified minute range
            df_filtered = df[(df['Minute'] >= minute_from) & (df['Minute'] <= minute_to)]

            # Initialize teams in the league table if not already done
            if home_team not in league_table:
                league_table[home_team] = {'points': 0, 'goals_scored': 0, 'goals_conceded': 0}
            if away_team not in league_table:
                league_table[away_team] = {'points': 0, 'goals_scored': 0, 'goals_conceded': 0}

            # Apply conditions for excluding goals
            if exclude_top_goalscorers:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(top_goalscorers['goalscorers']) &
                                          ~df_filtered['Away Scorer'].isin(top_goalscorers['goalscorers'])]

            if exclude_most_valuable_players:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(most_valuable_players['players']) &
                                          ~df_filtered['Away Scorer'].isin(most_valuable_players['players'])]

            if exclude_substituted_in_scorers:
                home_subs_in = df_filtered['Home Player In'].dropna().unique()
                away_subs_in = df_filtered['Away Player In'].dropna().unique()
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(home_subs_in) &
                                          ~df_filtered['Away Scorer'].isin(away_subs_in)]

            # Calculate goals for home and away teams
            home_goals_count = df_filtered[df_filtered['Home Event'] == 'Goal'].shape[0]
            away_goals_count = df_filtered[df_filtered['Away Event'] == 'Goal'].shape[0]

            # Update goals scored and conceded
            league_table[home_team]['goals_scored'] += home_goals_count
            league_table[home_team]['goals_conceded'] += away_goals_count
            league_table[away_team]['goals_scored'] += away_goals_count
            league_table[away_team]['goals_conceded'] += home_goals_count

            # Update points based on match result
            if home_goals_count > away_goals_count:
                league_table[home_team]['points'] += 3
            elif home_goals_count < away_goals_count:
                league_table[away_team]['points'] += 3
            else:
                league_table[home_team]['points'] += 1
                league_table[away_team]['points'] += 1

        except Exception as e:
            print(f"Error processing dataframe {df.name}: {e}")

    # Convert league table to a DataFrame
    league_df = pd.DataFrame.from_dict(league_table, orient='index')
    league_df['goal_difference'] = league_df['goals_scored'] - league_df['goals_conceded']

    # Sort the league table
    league_df = league_df.sort_values(by=['points', 'goal_difference', 'goals_scored'], ascending=False)
    league_df.reset_index(inplace=True)
    league_df.rename(columns={'index': 'Team'}, inplace=True)

    # Add rank with conditions
    league_df[''] = league_df.index + 1  # Adding 1 to make it 1-based index

    # Known final positions
    table_without_conditions = ["Leverkusen", "Stuttgart", "Bayern", "Leipzig", "Dortmund", "Frankfurt",
                                "Hoffenheim", "Heidenheim", "Bremen", "Freiburg", "Augsburg", "Wolfsburg",
                                "Mainz", "Mgladbach", "Union_Berlin", "Bochum", "Koln", "Darmstadt"]

    # Create DataFrame for known final positions
    known_positions = pd.DataFrame(table_without_conditions, columns=['Team'])
    known_positions['Rank_without_conditions'] = known_positions.index + 1  # Adding 1 to make it 1-based index

    # Merge calculated league table with known final positions
    merged_df = pd.merge(league_df, known_positions, on='Team', how='left')

    # Reset index to avoid displaying it
    merged_df.reset_index(drop=True, inplace=True)

    # Calculate position differences
    merged_df['Position_difference'] = merged_df['Rank_without_conditions'] - merged_df['']


    return merged_df[["","Team", "points", "goals_scored", "goals_conceded", "goal_difference", "Position_difference"]].style.hide(axis='index')

**Getting the squads of each team in the Bundesliga**

In [87]:
import pandas as pd

def calculate_league_table():
    # Prompt user for input
    minute_from = int(input("From which minute do you want goals to count? "))
    minute_to = int(input("To which minute do you want goals to count? "))

    exclude_top_goalscorers = input("Do goals from top scorers count? (Yes/No): ").strip().lower() == 'no'
    exclude_most_valuable_players = input("Do goals from most valuable players count? (Yes/No): ").strip().lower() == 'no'
    exclude_captains = input("Do goals from captains count? (Yes/No): ").strip().lower() == 'no'
    exclude_substituted_in_scorers = input("Do goals from substituted players count? (Yes/No): ").strip().lower() == 'no'

    # List of topscorers, most valuable players, and captains of each team
    top_goalscorers = pd.Series(["H. Kane","V. O. Boniface","B. Šeško","S. Guirassy","M. Beier","E. Demirović",
                                "D. Malen","M. Ducksch", "O. Marmoush", "J. Wind", "T. Kleindienst",
                                "R. Hack", "J. Burkardt","K. Stöger", "T. Skarke","V. Grifo","R. Gosens","D. Selke"])
    top_goalscorers = pd.DataFrame(top_goalscorers, columns=['goalscorers'])

    most_valuable_players = pd.Series(["J. Musiala", "F. Wirtz", "S. Guirassy", "X. Simons", "J. Brnadt", "R. K. Muani",
                                       "M. Beier",  "P. Wanner", "N. Füllkrug","R. Doan", "E. Demirović", "L. Majer",
                                       "B. Gruda", "M. Koné", "D. Doekhi","P. Osterhage","J. Chabot", "T. Skarke"])
    most_valuable_players = pd.DataFrame(most_valuable_players, columns=['players'])

    captains = pd.Series(["M. Neuer", "E. Can", "W. Orbán", "C. Trimmel", "C. Günter","L. Hradecky","S. Rode",
                          "M. Arnold", "S. Widmer","J. Omlin","F. Kainz", "O. Baumann","M. Friedl","A. Losilla","E. Demirović",
                          "W. Anton", "P. Mainka", "F. Holland"])
    captains = pd.DataFrame(captains, columns=['captains'])

    # Initialize league table and match count dictionaries
    league_table = {}
    match_count = {}

    for df in games_list:
        try:
            # Extract home and away team names from DataFrame name
            game_name = df.name
            if 'X' not in game_name:
                raise ValueError(f"Game name '{game_name}' is not in the correct format 'HomeTeamXAwayTeam'")

            home_team, away_team = game_name.split('X')

            # Ensure teams are initialized in the league table
            if home_team not in league_table:
                league_table[home_team] = {
                    'points': 0,
                    'goals_scored': 0,
                    'goals_conceded': 0,
                    'wins': 0,
                    'losses': 0,
                    'draws': 0
                }
                match_count[home_team] = 0
            if away_team not in league_table:
                league_table[away_team] = {
                    'points': 0,
                    'goals_scored': 0,
                    'goals_conceded': 0,
                    'wins': 0,
                    'losses': 0,
                    'draws': 0
                }
                match_count[away_team] = 0

            # Increment match count
            match_count[home_team] += 1
            match_count[away_team] += 1

            # Ensure necessary columns exist
            necessary_columns = ['Minute', 'Home Event', 'Away Event']
            if exclude_substituted_in_scorers:
                necessary_columns += ['Home Player In', 'Away Player In']

            missing_columns = [col for col in necessary_columns if col not in df.columns]

            if missing_columns:
                print(f"Missing columns: {missing_columns}. Assigning default values.")
                for col in missing_columns:
                    df[col] = None

            # Filter events to include only those within the specified minute range
            df_filtered = df[(df['Minute'] >= minute_from) & (df['Minute'] <= minute_to)]

            # Apply conditions for excluding goals
            if exclude_top_goalscorers:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(top_goalscorers['goalscorers']) &
                                          ~df_filtered['Away Scorer'].isin(top_goalscorers['goalscorers'])]

            if exclude_most_valuable_players:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(most_valuable_players['players']) &
                                          ~df_filtered['Away Scorer'].isin(most_valuable_players['players'])]

            if exclude_substituted_in_scorers:
                home_subs_in = df_filtered['Home Player In'].dropna().unique()
                away_subs_in = df_filtered['Away Player In'].dropna().unique()
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(home_subs_in) &
                                          ~df_filtered['Away Scorer'].isin(away_subs_in)]

            # Calculate goals for home and away teams
            home_goals_count = df_filtered[df_filtered['Home Event'] == 'Goal'].shape[0]
            away_goals_count = df_filtered[df_filtered['Away Event'] == 'Goal'].shape[0]

            # Update goals scored and conceded
            league_table[home_team]['goals_scored'] += home_goals_count
            league_table[home_team]['goals_conceded'] += away_goals_count
            league_table[away_team]['goals_scored'] += away_goals_count
            league_table[away_team]['goals_conceded'] += home_goals_count

            # Update points and statistics based on match result
            if home_goals_count > away_goals_count:
                league_table[home_team]['points'] += 3
                league_table[home_team]['wins'] += 1
                league_table[away_team]['losses'] += 1
            elif home_goals_count < away_goals_count:
                league_table[away_team]['points'] += 3
                league_table[away_team]['wins'] += 1
                league_table[home_team]['losses'] += 1
            else:
                league_table[home_team]['points'] += 1
                league_table[away_team]['points'] += 1
                league_table[home_team]['draws'] += 1
                league_table[away_team]['draws'] += 1

        except Exception as e:
            print(f"Error processing dataframe {df.name}: {e}")

    # Convert league table to a DataFrame
    league_df = pd.DataFrame.from_dict(league_table, orient='index')
    league_df['goal_difference'] = league_df['goals_scored'] - league_df['goals_conceded']
    league_df['matches_played'] = league_df.index.map(match_count)

    # Sort the league table
    league_df = league_df.sort_values(by=['points', 'goal_difference', 'goals_scored'], ascending=False)
    league_df.reset_index(inplace=True)
    league_df.rename(columns={'index': 'Team'}, inplace=True)

    # Add rank with conditions
    league_df['Rank'] = league_df.index + 1  # Adding 1 to make it 1-based index

    # Known final positions
    table_without_conditions = ["Leverkusen", "Stuttgart", "Bayern", "Leipzig", "Dortmund", "Frankfurt",
                                "Hoffenheim", "Heidenheim", "Bremen", "Freiburg", "Augsburg", "Wolfsburg",
                                "Mainz", "Mgladbach", "Union_Berlin", "Bochum", "Koln", "Darmstadt"]

    # Create DataFrame for known final positions
    known_positions = pd.DataFrame(table_without_conditions, columns=['Team'])
    known_positions['Rank_without_conditions'] = known_positions.index + 1  # Adding 1 to make it 1-based index

    # Merge calculated league table with known final positions
    merged_df = pd.merge(league_df, known_positions, on='Team', how='left')

    # Calculate position differences
    merged_df['Position_difference'] = merged_df['Rank_without_conditions'] - merged_df['Rank']

    # Reset index to avoid displaying it
    merged_df.reset_index(drop=True, inplace=True)

    # Return DataFrame without index
    return merged_df[["Rank", "Team", "matches_played", "wins", "draws", "losses", "goals_scored", "goals_conceded", "goal_difference", "points", "Position_difference"]].style.hide(axis='index')

In [88]:
calculate_league_table()

From which minute do you want goals to count? 1
To which minute do you want goals to count? 80
Do goals from top scorers count? (Yes/No): Yes
Do goals from most valuable players count? (Yes/No): No
Do goals from captains count? (Yes/No): Yes
Do goals from substituted players count? (Yes/No): No

In [133]:
import pandas as pd

def calculate_league_table():
    # Prompt user for input
    minute_from = int(input("From which minute do you want goals to count? "))
    minute_to = int(input("To which minute do you want goals to count? "))

    exclude_top_goalscorers = input("Do goals from top scorers count? (Yes/No): ").strip().lower() == 'no'
    exclude_most_valuable_players = input("Do goals from most valuable players count? (Yes/No): ").strip().lower() == 'no'
    exclude_captains = input("Do goals from captains count? (Yes/No): ").strip().lower() == 'no'
    exclude_substituted_in_scorers = input("Do goals from substituted players count? (Yes/No): ").strip().lower() == 'no'

    # List of topscorers, most valuable players, and captains of each team
    top_goalscorers = pd.Series(["H. Kane","V. O. Boniface","B. Šeško","S. Guirassy","M. Beier","E. Demirović",
                                "D. Malen","M. Ducksch", "O. Marmoush", "J. Wind", "T. Kleindienst",
                                "R. Hack", "J. Burkardt","K. Stöger", "T. Skarke","V. Grifo","R. Gosens","D. Selke"])
    top_goalscorers = pd.DataFrame(top_goalscorers, columns=['goalscorers'])

    most_valuable_players = pd.Series(["J. Musiala", "F. Wirtz", "S. Guirassy", "X. Simons", "J. Brnadt", "R. K. Muani",
                                       "M. Beier",  "P. Wanner", "N. Füllkrug","R. Doan", "E. Demirović", "L. Majer",
                                       "B. Gruda", "M. Koné", "D. Doekhi","P. Osterhage","J. Chabot", "T. Skarke"])
    most_valuable_players = pd.DataFrame(most_valuable_players, columns=['players'])

    captains = pd.Series(["M. Neuer", "E. Can", "W. Orbán", "C. Trimmel", "C. Günter","L. Hradecky","S. Rode",
                          "M. Arnold", "S. Widmer","J. Omlin","F. Kainz", "O. Baumann","M. Friedl","A. Losilla","E. Demirović",
                          "W. Anton", "P. Mainka", "F. Holland"])
    captains = pd.DataFrame(captains, columns=['captains'])

    # Initialize league table and match count dictionaries
    league_table = {}
    match_count = {}

    for df in games_list:
        try:
            # Extract home and away team names from DataFrame name
            game_name = df.name
            if 'X' not in game_name:
                raise ValueError(f"Game name '{game_name}' is not in the correct format 'HomeTeamXAwayTeam'")

            home_team, away_team = game_name.split('X')

            # Ensure teams are initialized in the league table
            if home_team not in league_table:
                league_table[home_team] = {
                    'Points': 0,
                    'G+': 0,
                    'G-': 0,
                    'W': 0,
                    'L': 0,
                    'D': 0
                }
                match_count[home_team] = 0
            if away_team not in league_table:
                league_table[away_team] = {
                    'Points': 0,
                    'G+': 0,
                    'G-': 0,
                    'W': 0,
                    'L': 0,
                    'D': 0
                }
                match_count[away_team] = 0

            # Increment match count
            match_count[home_team] += 1
            match_count[away_team] += 1

            # Ensure necessary columns exist
            necessary_columns = ['Minute', 'Home Event', 'Away Event']
            if exclude_substituted_in_scorers:
                necessary_columns += ['Home Player In', 'Away Player In']

            missing_columns = [col for col in necessary_columns if col not in df.columns]

            if missing_columns:
                print(f"Missing columns: {missing_columns}. Assigning default values.")
                for col in missing_columns:
                    df[col] = None

            # Filter events to include only those within the specified minute range
            df_filtered = df[(df['Minute'] >= minute_from) & (df['Minute'] <= minute_to)]

            # Apply conditions for excluding goals
            if exclude_top_goalscorers:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(top_goalscorers['goalscorers']) &
                                          ~df_filtered['Away Scorer'].isin(top_goalscorers['goalscorers'])]

            if exclude_most_valuable_players:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(most_valuable_players['players']) &
                                          ~df_filtered['Away Scorer'].isin(most_valuable_players['players'])]

            if exclude_substituted_in_scorers:
                home_subs_in = df_filtered['Home Player In'].dropna().unique()
                away_subs_in = df_filtered['Away Player In'].dropna().unique()
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(home_subs_in) &
                                          ~df_filtered['Away Scorer'].isin(away_subs_in)]

            # Calculate goals for home and away teams
            home_goals_count = df_filtered[df_filtered['Home Event'] == 'Goal'].shape[0]
            away_goals_count = df_filtered[df_filtered['Away Event'] == 'Goal'].shape[0]

            # Update goals scored and conceded
            league_table[home_team]['G+'] += home_goals_count
            league_table[home_team]['G-'] += away_goals_count
            league_table[away_team]['G+'] += away_goals_count
            league_table[away_team]['G-'] += home_goals_count

            # Update points and statistics based on match result
            if home_goals_count > away_goals_count:
                league_table[home_team]['Points'] += 3
                league_table[home_team]['W'] += 1
                league_table[away_team]['L'] += 1
            elif home_goals_count < away_goals_count:
                league_table[away_team]['Points'] += 3
                league_table[away_team]['W'] += 1
                league_table[home_team]['L'] += 1
            else:
                league_table[home_team]['Points'] += 1
                league_table[away_team]['Points'] += 1
                league_table[home_team]['D'] += 1
                league_table[away_team]['D'] += 1

        except Exception as e:
            print(f"Error processing dataframe {df.name}: {e}")

    # Convert league table to a DataFrame
    league_df = pd.DataFrame.from_dict(league_table, orient='index')
    league_df['+/-'] = league_df['G+'] - league_df['G-']
    league_df['Matches'] = league_df.index.map(match_count)

    # Sort the league table
    league_df = league_df.sort_values(by=['Points', '+/-', 'G+'], ascending=False)
    league_df.reset_index(inplace=True)
    league_df.rename(columns={'index': 'Team'}, inplace=True)

    # Add rank with conditions
    league_df["Position"] = league_df.index + 1  # Adding 1 to make it 1-based index

    # Known final positions
    table_without_conditions = ["Leverkusen", "Stuttgart", "Bayern", "Leipzig", "Dortmund", "Frankfurt",
                                "Hoffenheim", "Heidenheim", "Bremen", "Freiburg", "Augsburg", "Wolfsburg",
                                "Mainz", "Mgladbach", "Union_Berlin", "Bochum", "Koln", "Darmstadt"]

    # Create DataFrame for known final positions
    known_positions = pd.DataFrame(table_without_conditions, columns=['Team'])
    known_positions['Rank_without_conditions'] = known_positions.index + 1  # Adding 1 to make it 1-based index

    # Merge calculated league table with known final positions
    merged_df = pd.merge(league_df, known_positions, on='Team', how='left')

    merged_df[""] = '     '

    # Calculate position differences
    merged_df['Change'] = merged_df['Rank_without_conditions'] - merged_df["Position"]

    # Reset index to avoid displaying it
    merged_df.reset_index(drop=True, inplace=True)

    # Return DataFrame without index
    return merged_df[["Position", "Change", "Team","","","","","","","","","", "Matches", "W", "D", "L", "G+", "G-", "+/-", "Points"]].style.hide(axis='index')

In [134]:
calculate_league_table()

From which minute do you want goals to count? 1
To which minute do you want goals to count? 78
Do goals from top scorers count? (Yes/No): No
Do goals from most valuable players count? (Yes/No): Yes
Do goals from captains count? (Yes/No): Yes
Do goals from substituted players count? (Yes/No): No

In [127]:
import pandas as pd

def calculate_league_table():
    # Prompt user for input
    minute_from = int(input("From which minute do you want goals to count? "))
    minute_to = int(input("To which minute do you want goals to count? "))

    exclude_top_goalscorers = input("Do goals from top scorers count? (Yes/No): ").strip().lower() == 'no'
    exclude_most_valuable_players = input("Do goals from most valuable players count? (Yes/No): ").strip().lower() == 'no'
    exclude_captains = input("Do goals from captains count? (Yes/No): ").strip().lower() == 'no'
    exclude_substituted_in_scorers = input("Do goals from substituted players count? (Yes/No): ").strip().lower() == 'no'

    # List of topscorers, most valuable players, and captains of each team
    top_goalscorers = pd.Series(["H. Kane","V. O. Boniface","B. Šeško","S. Guirassy","M. Beier","E. Demirović",
                                "D. Malen","M. Ducksch", "O. Marmoush", "J. Wind", "T. Kleindienst",
                                "R. Hack", "J. Burkardt","K. Stöger", "T. Skarke","V. Grifo","R. Gosens","D. Selke"])
    top_goalscorers = pd.DataFrame(top_goalscorers, columns=['goalscorers'])

    most_valuable_players = pd.Series(["J. Musiala", "F. Wirtz", "S. Guirassy", "X. Simons", "J. Brnadt", "R. K. Muani",
                                       "M. Beier",  "P. Wanner", "N. Füllkrug","R. Doan", "E. Demirović", "L. Majer",
                                       "B. Gruda", "M. Koné", "D. Doekhi","P. Osterhage","J. Chabot", "T. Skarke"])
    most_valuable_players = pd.DataFrame(most_valuable_players, columns=['players'])

    captains = pd.Series(["M. Neuer", "E. Can", "W. Orbán", "C. Trimmel", "C. Günter","L. Hradecky","S. Rode",
                          "M. Arnold", "S. Widmer","J. Omlin","F. Kainz", "O. Baumann","M. Friedl","A. Losilla","E. Demirović",
                          "W. Anton", "P. Mainka", "F. Holland"])
    captains = pd.DataFrame(captains, columns=['captains'])

    # Initialize league table and match count dictionaries
    league_table = {}
    match_count = {}

    for df in games_list:
        try:
            # Extract home and away team names from DataFrame name
            game_name = df.name
            if 'X' not in game_name:
                raise ValueError(f"Game name '{game_name}' is not in the correct format 'HomeTeamXAwayTeam'")

            home_team, away_team = game_name.split('X')

            # Ensure teams are initialized in the league table
            if home_team not in league_table:
                league_table[home_team] = {
                    'Points': 0,
                    'G+': 0,
                    'G-': 0,
                    'W': 0,
                    'L': 0,
                    'D': 0
                }
                match_count[home_team] = 0
            if away_team not in league_table:
                league_table[away_team] = {
                    'Points': 0,
                    'G+': 0,
                    'G-': 0,
                    'W': 0,
                    'L': 0,
                    'D': 0
                }
                match_count[away_team] = 0

            # Increment match count
            match_count[home_team] += 1
            match_count[away_team] += 1

            # Ensure necessary columns exist
            necessary_columns = ['Minute', 'Home Event', 'Away Event']
            if exclude_substituted_in_scorers:
                necessary_columns += ['Home Player In', 'Away Player In']

            missing_columns = [col for col in necessary_columns if col not in df.columns]

            if missing_columns:
                print(f"Missing columns: {missing_columns}. Assigning default values.")
                for col in missing_columns:
                    df[col] = None

            # Filter events to include only those within the specified minute range
            df_filtered = df[(df['Minute'] >= minute_from) & (df['Minute'] <= minute_to)]

            # Apply conditions for excluding goals
            if exclude_top_goalscorers:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(top_goalscorers['goalscorers']) &
                                          ~df_filtered['Away Scorer'].isin(top_goalscorers['goalscorers'])]

            if exclude_most_valuable_players:
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(most_valuable_players['players']) &
                                          ~df_filtered['Away Scorer'].isin(most_valuable_players['players'])]

            if exclude_substituted_in_scorers:
                home_subs_in = df_filtered['Home Player In'].dropna().unique()
                away_subs_in = df_filtered['Away Player In'].dropna().unique()
                df_filtered = df_filtered[~df_filtered['Home Scorer'].isin(home_subs_in) &
                                          ~df_filtered['Away Scorer'].isin(away_subs_in)]

            # Calculate goals for home and away teams
            home_goals_count = df_filtered[df_filtered['Home Event'] == 'Goal'].shape[0]
            away_goals_count = df_filtered[df_filtered['Away Event'] == 'Goal'].shape[0]

            # Update goals scored and conceded
            league_table[home_team]['G+'] += home_goals_count
            league_table[home_team]['G-'] += away_goals_count
            league_table[away_team]['G+'] += away_goals_count
            league_table[away_team]['G-'] += home_goals_count

            # Update points and statistics based on match result
            if home_goals_count > away_goals_count:
                league_table[home_team]['Points'] += 3
                league_table[home_team]['W'] += 1
                league_table[away_team]['L'] += 1
            elif home_goals_count < away_goals_count:
                league_table[away_team]['Points'] += 3
                league_table[away_team]['W'] += 1
                league_table[home_team]['L'] += 1
            else:
                league_table[home_team]['Points'] += 1
                league_table[away_team]['Points'] += 1
                league_table[home_team]['D'] += 1
                league_table[away_team]['D'] += 1

        except Exception as e:
            print(f"Error processing dataframe {df.name}: {e}")

    # Convert league table to a DataFrame
    league_df = pd.DataFrame.from_dict(league_table, orient='index')
    league_df['+/-'] = league_df['G+'] - league_df['G-']
    league_df['Matches'] = league_df.index.map(match_count)

    # Sort the league table
    league_df = league_df.sort_values(by=['Points', '+/-', 'G+'], ascending=False)
    league_df.reset_index(inplace=True)
    league_df.rename(columns={'index': 'Team'}, inplace=True)

    # Add rank with conditions
    league_df["Position"] = league_df.index + 1  # Adding 1 to make it 1-based index

    # Known final positions
    table_without_conditions = ["Leverkusen", "Stuttgart", "Bayern", "Leipzig", "Dortmund", "Frankfurt",
                                "Hoffenheim", "Heidenheim", "Bremen", "Freiburg", "Augsburg", "Wolfsburg",
                                "Mainz", "Mgladbach", "Union_Berlin", "Bochum", "Koln", "Darmstadt"]

    # Create DataFrame for known final positions
    known_positions = pd.DataFrame(table_without_conditions, columns=['Team'])
    known_positions['Rank_without_conditions'] = known_positions.index + 1  # Adding 1 to make it 1-based index

    # Merge calculated league table with known final positions
    merged_df = pd.merge(league_df, known_positions, on='Team', how='left')

    merged_df[""] = '     '  # Adding a gap column

    # Calculate position differences
    merged_df['Change'] = merged_df['Rank_without_conditions'] - merged_df["Position"]

    # Reset index to avoid displaying it
    merged_df.reset_index(drop=True, inplace=True)

    # Apply styling
    styled_df = merged_df.style.set_properties(
        subset=['Team'],
        **{
            'text-align': 'left',
            'padding-left': '20px'  # Adjust the gap as needed
        }
    ).set_properties(
        subset=['Points'],
        **{
            'font-weight': 'bold'
        }
    ).hide(axis='index')

    result_df = styled_df.data[["Position", "Change", "Team", "", "", "", "Matches", "W", "D", "L", "G+", "G-", "+/-", "Points"]]

    return result_df

In [128]:
calculate_league_table()

From which minute do you want goals to count? 1
To which minute do you want goals to count? 90
Do goals from top scorers count? (Yes/No): Yes
Do goals from most valuable players count? (Yes/No): Yes
Do goals from captains count? (Yes/No): No
Do goals from substituted players count? (Yes/No): No

,Position,Change,Team,,,,Matches,W,D,L,G+,G-,+/-,Points
0,1,0,Leverkusen,,,,34,27,6,1,75,22,53,87
1,2,1,Bayern,,,,34,22,6,6,85,38,47,72
2,3,-1,Stuttgart,,,,34,20,7,7,66,36,30,67
3,4,1,Dortmund,,,,34,19,8,7,57,39,18,65
4,5,-1,Leipzig,,,,34,18,9,7,63,35,28,63
5,6,0,Frankfurt,,,,34,11,12,11,45,44,1,45
6,7,0,Hoffenheim,,,,34,12,8,14,59,57,2,44
7,8,1,Bremen,,,,34,11,10,13,38,44,-6,43
8,9,1,Freiburg,,,,34,11,10,13,37,49,-12,43
9,10,-2,Heidenheim,,,,34,8,15,11,45,49,-4,39
10,11,5,Bochum,,,,34,9,11,14,38,59,-21,38
11,12,2,Mgladbach,,,,34,8,13,13,46,55,-9,37
12,13,0,Mainz,,,,34,8,12,14,36,45,-9,36
13,14,-2,Wolfsburg,,,,34,10,6,18,35,52,-17,36
14,15,-4,Augsburg,,,,34,8,11,15,46,58,-12,35
15,16,1,Koln,,,,34,7,11,16,22,44,-22,32
16,17,-2,Union_Berlin,,,,34,8,7,19,24,48,-24,31
17,18,0,Darmstadt,,,,34,4,8,22,29,72,-43,20

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

# List of teams
teams = [
    "bayer-04-leverkusen/2681", "vfb-stuttgart/2677", "fc-bayern-munchen/2672",
    "borussia-dortmund/2673", "borussia-mgladbach/2527", "eintracht-frankfurt/2674",
    "fc-augsburg/2600", "rb-leipzig/36360", "sc-freiburg/2538", "tsg-hoffenheim/2569",
    "1-fc-union-berlin/2547", "vfl-wolfsburg/2524", "vfl-bochum-1848/2542",
    "sv-werder-bremen/2534", "1-fsv-mainz-05/2556", "1-fc-koln/2671",
    "darmstadt-98/2576", "1-fc-heidenheim/5885"
]

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
}

player_data = []

for team in teams:
    url = f"https://www.sofascore.com/team/football/{team}#tab:squad"
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, 'html.parser')
    players_div = soup.find_all('div', class_='Box dflyPx')

    for div in players_div:
        player_links = div.find_all('a', href=True)
        for player in player_links:
            player_name = player.get_text()
            team_name = team.split('/')[0].replace('-', ' ').title()
            player_data.append({"Team": team_name, "Player": player_name})

# Convert to DataFrame
df_players = pd.DataFrame(player_data)

# Function to extract the required details
def extract_details(player_str):
    # Regular expression pattern to match the player name, number, age, and country
    pattern = re.compile(r'^(.*?)(\d{1,2})(\d{2})\s*yrs(\w{3})$')
    match = pattern.match(player_str)
    if match:
        player_name = match.group(1).strip()
        number = match.group(2)
        age = match.group(3)
        country = match.group(4)
        return player_name, number, int(age), country
    else:
        # Handle cases where there's no shirt number but only age
        pattern_age_only = re.compile(r'^(.*?)(\d{2})\s*yrs(\w{3})$')
        match_age_only = pattern_age_only.match(player_str)
        if match_age_only:
            player_name = match_age_only.group(1).strip()
            number = None
            age = match_age_only.group(2)
            country = match_age_only.group(3)
            return player_name, number, int(age), country
        else:
            # Handle cases where the pattern doesn't match
            parts = player_str.split()
            player_name = ' '.join(parts[:-3])
            number = None
            age = None
            country = None
            if len(parts) >= 3:
                number = parts[-3][:2]  # Extract the first 2 digits as shirt number if available
                age = parts[-3][2:]     # Extract the remaining digits as age if available
                country = parts[-2]     # Extract the country abbreviation
            return player_name, number, age, country

# Apply the function to the DataFrame
df_players[['Player', 'Number', 'Age', 'Country']] = df_players['Player'].apply(lambda x: pd.Series(extract_details(x)))

# Print the DataFrame with the new columns
print(df_players)

# Split into separate DataFrames for each team
team_dfs = {}
grouped = df_players.groupby('Team')

for team, data in grouped:
    team_dfs[team] = data.reset_index(drop=True)

# Print the first few rows of each team DataFrame to verify
for team, df in team_dfs.items():
    print(f"Team: {team}")
    print(df.head())
    print("\n")


# Access a specific team DataFrame
Stuttgart = team_dfs["Vfb Stuttgart"]
Leipzig = team_dfs["Rb Leipzig"]
Freiburg = team_dfs["Sc Freiburg"]
Bremen = team_dfs["Sv Werder Bremen"]
Hoffenheim = team_dfs["Tsg Hoffenheim"]
Gladbach = team_dfs["Borussia Mgladbach"]
Darmstadt = team_dfs["Darmstadt 98"]
Dortmund = team_dfs["Borussia Dortmund"]
Leverkusen = team_dfs["Bayer 04 Leverkusen"]
Mainz = team_dfs["1 Fsv Mainz 05"]
Koln = team_dfs["1 Fc Koln"]
Heidenheim = team_dfs["1 Fc Heidenheim"]
Frankfurt = team_dfs["Eintracht Frankfurt"]
Augsburg = team_dfs["Fc Augsburg"]
Bayern = team_dfs["Fc Bayern Munchen"]
Bochum = team_dfs["Vfl Bochum 1848"]
Wolfsburg = team_dfs["Vfl Wolfsburg"]
Union_Berlin = team_dfs["1 Fc Union Berlin"]


def transform_name(name):
    if not name:  # Check if name is empty or None
        return name
    parts = name.split()
    if len(parts) < 2:  # Check if name does not have at least a first and last name
        return name
    first_initial = parts[0][0]
    last_name = parts[-1]
    return f"{first_initial}. {last_name}"

# Iterate over the DataFrames in the dictionary and apply the transformation
for team, df in team_dfs.items():
    df['Player'] = df['Player'].apply(transform_name)

#Transfers for each team
Stuttgart_additions = [
    {'Team': 'Vfb Stuttgart', 'Player': 'H. Ito', 'Number': 99, 'Age': 25.0, 'Country': 'JPN'},
    {'Team': 'Vfb Stuttgart', 'Player': 'W. Anton', 'Number': 98, 'Age': 27.0, 'Country': 'GER'},
     {'Team': 'Vfb Stuttgart', 'Player': 'S. Guirassy', 'Number': 97, 'Age': 28.0, 'Country': 'GUI'},
    {'Team': 'Vfb Stuttgart', 'Player': 'D. Undav', 'Number': 96, 'Age': 28.0, 'Country': 'GER'},
     {'Team': 'Vfb Stuttgart', 'Player': 'L. Stergiou', 'Number': 95, 'Age': 22.0, 'Country': 'SUI'},
     {'Team': 'Vfb Stuttgart', 'Player': 'M. Dahoud', 'Number': 93, 'Age': 28.0, 'Country': 'GER'},
    {'Team': 'Vfb Stuttgart', 'Player': 'W. Anton', 'Number': 92, 'Age': 27.0, 'Country': 'GER'}
]


Stuttgart_additions_df = pd.DataFrame(Stuttgart_additions)

# Append new players to the Stuttgart DataFrame
Stuttgart = pd.concat([Stuttgart, Stuttgart_additions_df], ignore_index=True)

Stuttgart_players_to_remove = ["E. Demirović",'J. Chabot', 'Y. Keitel', 'N. Woltemade', 'L. Pfeiffer']

# Remove rows with specified players
Stuttgart = Stuttgart[~Stuttgart['Player'].isin(Stuttgart_players_to_remove)]

Leipzig_additions = [
    {'Team': 'Rb Leipzig', 'Player': 'X. Simons', 'Number': 99, 'Age': 21.0, 'Country': 'NED'},
    {'Team': 'Rb Leipzig', 'Player': 'E. Forsberg', 'Number': 98, 'Age': 32.0, 'Country': 'SWE'},
     {'Team': 'Rb Leipzig', 'Player': 'T. Werner', 'Number': 97, 'Age': 28.0, 'Country': 'GER'},
   ]


Leipzig_additions_df = pd.DataFrame(Leipzig_additions)

# Append new players to the Stuttgart DataFrame
Leipzig = pd.concat([Leipzig, Leipzig_additions_df], ignore_index=True)

Freiburg_additions = [
    {'Team': 'Sc Freiburg', 'Player': 'Y. Keitel', 'Number': 99, 'Age': 24.0, 'Country': 'GER'},
    {'Team': 'Sc Freiburg', 'Player': 'M. Philipp', 'Number': 98, 'Age': 30.0, 'Country': 'GER'},
]


Freiburg_additions_df = pd.DataFrame(Freiburg_additions)

# Append new players to the Stuttgart DataFrame
Freiburg = pd.concat([Freiburg, Freiburg_additions_df], ignore_index=True)

# List of Freiburg players to remove
Freiburg_players_to_remove = ["E. Dinkçi", "P. Osterhage", "M. Philipp", "K. Schlotterbeck"]

# Remove rows with specified players
Freiburg = Freiburg[~Freiburg['Player'].isin(Freiburg_players_to_remove)]


Bremen_additions = [
    {'Team': 'Sv Werder Bremen', 'Player': 'R. Borré', 'Number': 99, 'Age': 28.0, 'Country': 'COL'},
    {'Team': 'Sv Werder Bremen', 'Player': 'N. Woltemade', 'Number': 98, 'Age': 22.0, 'Country': 'GER'},
     {'Team': 'Sv Werder Bremen', 'Player': 'S. Alvero', 'Number': 97, 'Age': 22.0, 'Country': 'FRA'},
    {'Team': 'Sv Werder Bremen', 'Player': 'C. Groß', 'Number': 96, 'Age': 35.0, 'Country': 'GER'},
    ]


Bremen_additions_df = pd.DataFrame(Bremen_additions)

# Append new players to the Stuttgart DataFrame
Bremen = pd.concat([Bremen, Bremen_additions_df], ignore_index=True)

Hoffenheim_additions = [
    {'Team': 'Tsg Hoffenheim', 'Player': 'W. Weghorst', 'Number': 99, 'Age': 31.0, 'Country': 'NED'},
    {'Team': 'Tsg Hoffenheim', 'Player': 'J. Brooks', 'Number': 98, 'Age': 31.0, 'Country': 'USA'},
     {'Team': 'Tsg Hoffenheim', 'Player': 'R. Skov', 'Number': 97, 'Age': 28.0, 'Country': 'DEN'},
]


Hoffenheim_additions_df = pd.DataFrame(Hoffenheim_additions)

# Append new players to the Stuttgart DataFrame
Hoffenheim = pd.concat([Hoffenheim, Hoffenheim_additions_df], ignore_index=True)

# List of Freiburg players to remove
Hoffenheim_players_to_remove = ["J. Justvan"]

# Remove rows with specified players
Hoffenheim = Hoffenheim[~Hoffenheim['Player'].isin(Hoffenheim_players_to_remove)]

Gladbach_additions = [
    {'Team': 'Borussia Mgladbach', 'Player': 'J. Siebatcheu', 'Number': 99, 'Age': 28.0, 'Country': 'USA'},
    {'Team': 'Borussia Mgladbach', 'Player': 'M. Wöber', 'Number': 98, 'Age': 26.0, 'Country': 'AUT'},
]


Gladbach_additions_df = pd.DataFrame(Gladbach_additions)

# Append new players to the Stuttgart DataFrame
Gladbach = pd.concat([Gladbach, Gladbach_additions_df], ignore_index=True)

Gladbach_players_to_remove = ["T. Kleindienst", "K. Stöger"]

# Remove rows with specified players
Gladbach = Gladbach[~Gladbach['Player'].isin(Gladbach_players_to_remove)]

Darmstadt_additions = [
    {'Team': 'Darmstadt 98', 'Player': 'C. Klarer', 'Number': 99, 'Age': 24.0, 'Country': 'AUT'},
    {'Team': 'Darmstadt 98', 'Player': 'M. Honsak', 'Number': 98, 'Age': 27.0, 'Country': 'AUT'},
     {'Team': 'Darmstadt 98', 'Player': 'E. Karić', 'Number': 99, 'Age': 27.0, 'Country': 'AUT'},
    {'Team': 'Darmstadt 98', 'Player': 'J. Müller', 'Number': 98, 'Age': 30.0, 'Country': 'GER'},
     {'Team': 'Darmstadt 98', 'Player': 'T. Skarke', 'Number': 99, 'Age': 27.0, 'Country': 'GER'},
    {'Team': 'Darmstadt 98', 'Player': 'M. Maglica', 'Number': 98, 'Age': 25.0, 'Country': 'CRO'},
{'Team': 'Darmstadt 98', 'Player': 'B. Franjić', 'Number': 99, 'Age': 24.0, 'Country': 'CRO'},
    {'Team': 'Darmstadt 98', 'Player': 'J. Justvan', 'Number': 98, 'Age': 26.0, 'Country': 'GER'},
    {'Team': 'Darmstadt 98', 'Player': 'A. Seydel', 'Number': 99, 'Age': 24.0, 'Country': 'GER'},
    {'Team': 'Darmstadt 98', 'Player': 'L. Pfeiffer', 'Number': 99, 'Age': 27.0, 'Country': 'GER'},
  ]


Darmstadt_additions_df = pd.DataFrame(Darmstadt_additions)

# Append new players to the Stuttgart DataFrame
Darmstad = pd.concat([Darmstadt, Darmstadt_additions_df], ignore_index=True)



Dortmund_additions = [
    {'Team': 'Borussia Dortmund', 'Player': 'M. Reus', 'Number': 99, 'Age': 35.0, 'Country': 'GER'},
    {'Team': 'Borussia Dortmund', 'Player': 'M. Hummels', 'Number': 98, 'Age': 35.0, 'Country': 'GER'},
     {'Team': 'Borussia Dortmund', 'Player': 'M. Wolf', 'Number': 99, 'Age': 29.0, 'Country': 'GER'},
    {'Team': 'Borussia Dortmund', 'Player': 'I. Maatsen', 'Number': 98, 'Age': 22.0, 'Country': 'NED'},
     {'Team': 'Borussia Dortmund', 'Player': 'J. Sancho', 'Number': 99, 'Age': 24.0, 'Country': 'ENG'},
  ]


Dortmund_additions_df = pd.DataFrame(Dortmund_additions)

# Append new players to the Stuttgart DataFrame
Dortmund = pd.concat([Dortmund, Dortmund_additions_df], ignore_index=True)

Dortmund_players_to_remove = ["S. Guirassy", "W. Anton"]

# Remove rows with specified players
Dortmund = Dortmund[~Dortmund['Player'].isin(Dortmund_players_to_remove)]

Leverkusen_additions = [
    {'Team': 'Bayer 04 Leverkusen', 'Player': 'J. Stanišić', 'Number': 99, 'Age': 24.0, 'Country': 'CRO'},
   ]


Leverkusen_additions_df = pd.DataFrame(Leverkusen_additions)

# Append new players to the Stuttgart DataFrame
Leverkusen = pd.concat([Leverkusen, Leverkusen_additions_df], ignore_index=True)

Mainz_additions = [
    {'Team': '1 Fsv Mainz 05', 'Player': 'L. Barreiro', 'Number': 99, 'Age': 24.0, 'Country': 'LUX'},
    {'Team': '1 Fsv Mainz 05', 'Player': 'L. Ajorque', 'Number': 99, 'Age': 30.0, 'Country': 'FRA'},
    {'Team': '1 Fsv Mainz 05', 'Player': 'S. van den Berg', 'Number': 99, 'Age': 22.0, 'Country': 'NED'}
   ]


Mainz_additions_df = pd.DataFrame(Mainz_additions)

# Append new players to the Stuttgart DataFrame
Mainz = pd.concat([Mainz, Mainz_additions_df], ignore_index=True)

Koln_additions = [
    {'Team': '1 Fc Koln', 'Player': 'J. Chabot', 'Number': 99, 'Age': 26.0, 'Country': 'GER'},
    {'Team': '1 Fc Koln', 'Player': 'D. Selke', 'Number': 99, 'Age': 29.0, 'Country': 'GER'},
    {'Team': '1 Fc Koln', 'Player': 'B. Schmitz', 'Number': 99, 'Age': 29.0, 'Country': 'GER'},
    {'Team': '1 Fc Koln', 'Player': 'L. Waldschmidt', 'Number': 99, 'Age': 28.0, 'Country': 'GER'},
    {'Team': '1 Fc Koln', 'Player': 'F. Alidou', 'Number': 99, 'Age': 23.0, 'Country': 'GER'},
    {'Team': '1 Fc Koln', 'Player': 'R. Carstensen', 'Number': 99, 'Age': 23.0, 'Country': 'DEN'}
   ]


Koln_additions_df = pd.DataFrame(Koln_additions)

# Append new players to the Stuttgart DataFrame
Koln = pd.concat([Koln, Koln_additions_df], ignore_index=True)

Heidenheim_additions = [
    {'Team': '1 Fc Heidenheim', 'Player': 'J. Beste', 'Number': 99, 'Age': 25.0, 'Country': 'GER'},
    {'Team': '1 Fc Heidenheim', 'Player': 'T. Kleindienst', 'Number': 99, 'Age': 28.0, 'Country': 'GER'},
    {'Team': '1 Fc Heidenheim', 'Player': 'K. Sessa', 'Number': 99, 'Age': 24.0, 'Country': 'GER'},
    {'Team': '1 Fc Heidenheim', 'Player': 'N. Dovedan', 'Number': 99, 'Age': 30.0, 'Country': 'AUT'},
    {'Team': '1 Fc Heidenheim', 'Player': 'F. Pick', 'Number': 99, 'Age': 28.0, 'Country': 'GER'},
    {'Team': '1 Fc Heidenheim', 'Player': 'C. Kühlwetter', 'Number': 99, 'Age': 28.0, 'Country': 'GER'},
    {'Team': '1 Fc Heidenheim', 'Player': 'E. Dinkçi', 'Number': 99, 'Age': 22.0, 'Country': 'TUR'}
   ]


Heidenheim_additions_df = pd.DataFrame(Heidenheim_additions)

# Append new players to the Stuttgart DataFrame
Heidenheim = pd.concat([Heidenheim, Heidenheim_additions_df], ignore_index=True)

Heidenheim_players_to_remove = ["M. Kaufmann"]

# Remove rows with specified players
Heidenheim = Heidenheim[~Heidenheim['Player'].isin(Heidenheim_players_to_remove)]

Frankfurt_additions = [
    {'Team': 'Eintracht Frankfurt', 'Player': 'H. Smločić', 'Number': 99, 'Age': 23.0, 'Country': 'CRO'},
    {'Team': 'Eintracht Frankfurt', 'Player': 'N. Ferri', 'Number': 99, 'Age': 19.0, 'Country': 'ESP'},
    {'Team': 'Eintracht Frankfurt', 'Player': 'H. Ekitiké', 'Number': 99, 'Age': 22.0, 'Country': 'FRA'},
    {'Team': 'Eintracht Frankfurt', 'Player': 'R. Koch', 'Number': 99, 'Age': 27.0, 'Country': 'GER'},
      ]


Frankfurt_additions_df = pd.DataFrame(Frankfurt_additions)

# Append new players to the Stuttgart DataFrame
Frankfurt = pd.concat([Frankfurt, Frankfurt_additions_df], ignore_index=True)

Frankfurt_players_to_remove = ["K. Jakić", "F. Alidou", "J. Ngankam"]

# Remove rows with specified players
Frankfurt = Frankfurt[~Frankfurt['Player'].isin(Frankfurt_players_to_remove)]

Augsburg_additions = [
    {'Team': 'Fc Augsburg', 'Player': 'E. Demirović', 'Number': 99, 'Age': 26.0, 'Country': 'BIH'},
    {'Team': 'Fc Augsburg', 'Player': 'D. Beljo', 'Number': 99, 'Age': 22.0, 'Country': 'CRO'},
    {'Team': 'Fc Augsburg', 'Player': 'S. Michel', 'Number': 99, 'Age': 33.0, 'Country': 'GER'},
    {'Team': 'Fc Augsburg', 'Player': 'I. Borduchi', 'Number': 99, 'Age': 27.0, 'Country': 'BRA'},
    {'Team': 'Fc Augsburg', 'Player': 'K. Jakić', 'Number': 99, 'Age': 27.0, 'Country': 'CRO'},
    {'Team': 'Fc Augsburg', 'Player': 'K. Mbabu', 'Number': 99, 'Age': 29.0, 'Country': 'SUI'}
      ]


Augsburg_additions_df = pd.DataFrame(Augsburg_additions)

# Append new players to the Stuttgart DataFrame
Augsburg = pd.concat([Augsburg, Augsburg_additions_df], ignore_index=True)

Augsburg = Augsburg[~Augsburg['Player'].isin(["K. Schlotterbeck"])]

Bayern_additions = [
    {'Team': 'Fc Bayern Munchen', 'Player': 'L. Zvonarek', 'Number': 99, 'Age': 19.0, 'Country': 'CRO'},
    {'Team': 'Fc Bayern Munchen', 'Player': 'E. Choupo-Moting', 'Number': 99, 'Age': 35.0, 'Country': 'CMR'},
    {'Team': 'Fc Bayern Munchen', 'Player': 'S. Michel', 'Number': 99, 'Age': 33.0, 'Country': 'GER'},
    {'Team': 'Fc Bayern Munchen', 'Player': 'I. Borduchi', 'Number': 99, 'Age': 27.0, 'Country': 'BRA'},
    {'Team': 'Fc Bayern Munchen', 'Player': 'K. Jakić', 'Number': 99, 'Age': 27.0, 'Country': 'CRO'},
    {'Team': 'Fc Bayern Munchen', 'Player': 'K. Mbabu', 'Number': 99, 'Age': 29.0, 'Country': 'SUI'}
      ]


Bayern_additions_df = pd.DataFrame(Bayern_additions)

# Append new players to the Stuttgart DataFrame
Bayern = pd.concat([Bayern, Bayern_additions_df], ignore_index=True)

Bayern_players_to_remove = ["H. Ito", "J. Stanišić"]

# Remove rows with specified players
Bayern = Bayern[~Bayern['Player'].isin(Bayern_players_to_remove)]

Bochum_additions = [
    {'Team': 'Vfl Bochum 1848', 'Player': 'P. Osterhage', 'Number': 99, 'Age': 24.0, 'Country': 'GER'},
    {'Team': 'Vfl Bochum 1848', 'Player': 'K. Stöger', 'Number': 99, 'Age': 30.0, 'Country': 'GER'},
    {'Team': 'Vfl Bochum 1848', 'Player': 'T. Asano', 'Number': 99, 'Age': 29.0, 'Country': 'JPN'},
    {'Team': 'Vfl Bochum 1848', 'Player': 'C. Antwi-Adjei', 'Number': 99, 'Age': 30.0, 'Country': 'GHA'},
    {'Team': 'Vfl Bochum 1848', 'Player': 'K. Schlotterbeck', 'Number': 99, 'Age': 27.0, 'Country': 'GER'},
    {'Team': 'Vfl Bochum 1848', 'Player': 'I. Ordets', 'Number': 99, 'Age': 31.0, 'Country': 'UKR'},
    {'Team': 'Vfl Bochum 1848', 'Player': 'G. Paciência', 'Number': 99, 'Age': 29.0, 'Country': 'POR'}
      ]


Bochum_additions_df = pd.DataFrame(Bochum_additions)

# Append new players to the Stuttgart DataFrame
Bochum = pd.concat([Bochum, Bochum_additions_df], ignore_index=True)


Wolfsburg_additions = [
    {'Team': 'Vfl Wolfsburg', 'Player': 'V. Černý', 'Number': 99, 'Age': 26.0, 'Country': 'CZE'},
      ]


Wolfsburg_additions_df = pd.DataFrame(Wolfsburg_additions)

# Append new players to the Stuttgart DataFrame
Wolfsburg = pd.concat([Wolfsburg, Wolfsburg_additions_df], ignore_index=True)

Union_Berlin_additions = [
    {'Team': '1 Fc Union Berlin', 'Player': 'A. Laïdouni', 'Number': 99, 'Age': 27.0, 'Country': 'TUN'},
    {'Team': '1 Fc Union Berlin', 'Player': 'M. Kaufmann', 'Number': 99, 'Age': 23.0, 'Country': 'DEN'},
    {'Team': '1 Fc Union Berlin', 'Player': 'R. Knoche', 'Number': 99, 'Age': 32.0, 'Country': 'GER'},
    {'Team': '1 Fc Union Berlin', 'Player': 'A: Král', 'Number': 99, 'Age': 26.0, 'Country': 'CZE'},
    {'Team': '1 Fc Union Berlin', 'Player': 'B. Aaronson', 'Number': 99, 'Age': 23.0, 'Country': 'USA'}
      ]


Union_Berlin_additions_df = pd.DataFrame(Union_Berlin_additions)

# Append new players to the Stuttgart DataFrame
Union_Berlin = pd.concat([Union_Berlin, Union_Berlin_additions_df], ignore_index=True)

# List of Union_Berlin players to remove
Union_Berlin_players_to_remove = ["T. Skarke", "J. Siebatcheu"]

# Remove rows with specified players
Union_Berlin = Union_Berlin[~Union_Berlin['Player'].isin(Union_Berlin_players_to_remove)]

                    Team                Player Number Age Country
0    Bayer 04 Leverkusen         Florian Wirtz     10  21     GER
1    Bayer 04 Leverkusen  Victor Okoh Boniface     22  23     NGR
2    Bayer 04 Leverkusen            Amine Adli     21  24     MAR
3    Bayer 04 Leverkusen         Patrik Schick     14  28     CZE
4    Bayer 04 Leverkusen           Adam Hložek     17  22     CZE
..                   ...                   ...    ...  ..     ...
537      1 Fc Heidenheim       Nick Rothweiler     45  18     GER
538      1 Fc Heidenheim          Kevin Müller      1  33     GER
539      1 Fc Heidenheim       Paul Tschernuth     34  22     AUT
540      1 Fc Heidenheim          Vitus Eicher     22  33     GER
541      1 Fc Heidenheim          Frank Feller     40  20     GER

[542 rows x 5 columns]
Team: 1 Fc Heidenheim
              Team              Player Number Age Country
0  1 Fc Heidenheim     Mikkel Kaufmann     29  23     DEN
1  1 Fc Heidenheim    Marvin Pieringer     18  24     GER
2  1 Fc Heidenheim         Leo Scienza      8  25     BRA
3  1 Fc Heidenheim      Sirlord Conteh     31  28     GER
4  1 Fc Heidenheim  Maximilian Breunig     14  23     GER


Team: 1 Fc Koln
        Team               Player Number Age Country
0  1 Fc Koln       Sargis Adamyan     23  31     ARM
1  1 Fc Koln       Steffen Tigges     21  26     GER
2  1 Fc Koln         Tim Lemperle     19  22     GER
3  1 Fc Koln         Damion Downs     42  20     USA
4  1 Fc Koln  Jaka Cuber Potocnik     43  19     SLO


Team: 1 Fc Union Berlin
                Team             Player Number Age Country
0  1 Fc Union Berlin      Kevin Volland     10  32     GER
1  1 Fc Union Berlin    Yorbe Vertessen      7  23     BEL
2  1 Fc Union Berlin  Jordan Siebatcheu     17  28     USA
3  1 Fc Union Berlin        Chris Bedia     11  28     CIV
4  1 Fc Union Berlin       Ivan Prtajin      9  28     CRO


Team: 1 Fsv Mainz 05
             Team             Player Number Age Country
0  1 Fsv Mainz 05  Jonathan Burkardt     29  24     GER
1  1 Fsv Mainz 05      Karim Onisiwo      9  32     AUT
2  1 Fsv Mainz 05       Armindo Sieb     11  21     GER
3  1 Fsv Mainz 05      Nelson Weiper     44  19     GER
4  1 Fsv Mainz 05       Jae-sung Lee      7  31     KOR


Team: Bayer 04 Leverkusen
                  Team                Player Number Age Country
0  Bayer 04 Leverkusen         Florian Wirtz     10  21     GER
1  Bayer 04 Leverkusen  Victor Okoh Boniface     22  23     NGR
2  Bayer 04 Leverkusen            Amine Adli     21  24     MAR
3  Bayer 04 Leverkusen         Patrik Schick     14  28     CZE
4  Bayer 04 Leverkusen           Adam Hložek     17  22     CZE


Team: Borussia Dortmund
                Team             Player Number Age Country
0  Borussia Dortmund   Sébastien Haller      9  30     CIV
1  Borussia Dortmund    Serhou Guirassy      9  28     GUI
2  Borussia Dortmund  Youssoufa Moukoko     18  19     GER
3  Borussia Dortmund      Karim Adeyemi     27  22     GER
4  Borussia Dortmund    Niclas Füllkrug     14  31     GER


Team: Borussia Mgladbach
                 Team            Player Number Age Country
0  Borussia Mgladbach     Alassane Pléa     14  31     FRA
1  Borussia Mgladbach  Grant-Leon Ranos     28  21     ARM
2  Borussia Mgladbach   Tim Kleindienst     11  28     GER
3  Borussia Mgladbach    Tomáš Čvančara     31  23     CZE
4  Borussia Mgladbach       Shio Fukuda     13  20     JPN


Team: Darmstadt 98
           Team             Player Number Age Country
0  Darmstadt 98  Oscar Vilhelmsson     29  20     SWE
1  Darmstadt 98  Filip Stojilković     25  24     SUI
2  Darmstadt 98      Fraser Hornby      9  24     SCO
3  Darmstadt 98    Fabio Torsiello     64  19     GER
4  Darmstadt 98     Luca Marseiler     99  27     GER


Team: Eintracht Frankfurt
                  Team          Player Number Age Country
0  Eintracht Frankfurt   Omar Marmoush      7  25     EGY
1  Eintracht Frankfurt    Farès Chaïbi      8  21     ALG
2  Eintracht Frankfurt    Hugo Ekitiké     11  22     FRA
3  Eintracht Frankfurt   Ansgar Knauff     36  22     GER
4  Eintracht Frankfurt  Igor Matanović      9  21     CRO


Team: Fc Augsburg
          Team           Player Number Age Country
0  Fc Augsburg     Steve Mounié     15  29     BEN
1  Fc Augsburg   Samuel Essende     29  26     COD
2  Fc Augsburg  Nathanaël Mbuku     11  22     FRA
3  Fc Augsburg    Phillip Tietz     21  27     GER
4  Fc Augsburg   Yusuf Kabadayi      7  20     GER


Team: Fc Bayern Munchen
                Team              Player Number Age Country
0  Fc Bayern Munchen          Harry Kane      9  31     ENG
1  Fc Bayern Munchen       Michael Olise      7  22     FRA
2  Fc Bayern Munchen          Mathys Tel     39  19     FRA
3  Fc Bayern Munchen  Arijon Ibrahimović     20  18     GER
4  Fc Bayern Munchen       Jamal Musiala     42  21     GER


Team: Rb Leipzig
         Team          Player Number Age Country
0  Rb Leipzig     Loïs Openda     11  24     BEL
1  Rb Leipzig  Benjamin Šeško     30  21     SLO
2  Rb Leipzig     André Silva     21  28     POR
3  Rb Leipzig  Yussuf Poulsen      9  30     DEN
4  Rb Leipzig   Robert Ramsak      9  17     GER


Team: Sc Freiburg
          Team               Player Number Age Country
0  Sc Freiburg        Roland Sallai     22  27     HUN
1  Sc Freiburg  Michael Gregoritsch     38  30     AUT
2  Sc Freiburg    Chukwubuike Adamu     20  23     AUT
3  Sc Freiburg   Maximilian Philipp     26  30     GER
4  Sc Freiburg          Lucas Höler      9  30     GER


Team: Sv Werder Bremen
               Team              Player Number Age Country
0  Sv Werder Bremen      Dawid Kownacki      9  27     POL
1  Sv Werder Bremen  Isak Hansen Aarøen     21  19     NOR
2  Sv Werder Bremen      Marvin Ducksch      7  30     GER
3  Sv Werder Bremen      Justin Njinmah     11  23     GER
4  Sv Werder Bremen           Keke Topp     42  20     GER


Team: Tsg Hoffenheim
             Team            Player Number Age Country
0  Tsg Hoffenheim   Andrej Kramarić     27  33     CRO
1  Tsg Hoffenheim  Maximilian Beier     46  21     GER
2  Tsg Hoffenheim    Mergim Berisha     99  26     GER
3  Tsg Hoffenheim       Ihlas Bebou      9  30     TOG
4  Tsg Hoffenheim     Max Moerstedt     33  18     GER


Team: Vfb Stuttgart
            Team                Player Number Age Country
0  Vfb Stuttgart  Silas Katompa Mvumpa     14  25     COD
1  Vfb Stuttgart     Ermedin Demirović      9  26     BIH
2  Vfb Stuttgart          Wahid Faghir     29  21     DEN
3  Vfb Stuttgart        Mohamed Sankoh     44  20     NED
4  Vfb Stuttgart        Nick Woltemade     11  22     GER


Team: Vfl Bochum 1848
              Team              Player Number Age Country
0  Vfl Bochum 1848     Philipp Hofmann     33  31     GER
1  Vfl Bochum 1848     Gerrit Holtmann     21  29     PHI
2  Vfl Bochum 1848  Moritz Broschinski     29  23     GER
3  Vfl Bochum 1848         Dani de Wit     10  26     NED
4  Vfl Bochum 1848    Ibrahima Sissoko      6  26     MLI


Team: Vfl Wolfsburg
            Team                   Player Number Age Country
0  Vfl Wolfsburg  Mohamed El Amine Amoura      9  24     ALG
1  Vfl Wolfsburg               Jonas Wind     23  25     DEN
2  Vfl Wolfsburg           Bartosz Białek     17  22     POL
3  Vfl Wolfsburg              Tiago Tomás     11  22     POR
4  Vfl Wolfsburg             Lukas Nmecha     10  25     GER

Extracting the top scorer and top assist provider from each team

**Creating the league table**

**Defining home and away team from the html**